#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/stir
#
# IDENTIFICATION
#    src/backend/access/stir/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/stir
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	stir.o

include $(top_srcdir)/src/backend/common.mk
