DROP TABLE IF EXISTS t1 CASCADE;

LOAD 'sqlol';

\;\; SELECT 1\;

CREATE TABLE t1 (id integer, val text);

HAI 1.2 I HAS A t1 GIMMEH id, "val" KTHXBYE\g

HAI 1.2 MAEK I HAS A t1 GIMMEH id, "val" A v0 KTHXBYE\g

CREATE VIEW v1 AS SELECT * FROM t1\; CREATE VIEW v2 AS SELECT * FROM t1\;HAI 1.2 I HAS A t1 GIMMEH "id", id KTHXBYE\g

CREATE VIEW v3 AS SELECT * FROM t1\; HAI 1.2 MAEK I HAS A t1 GIMMEH id, "val" A v4 KTHXBYE CREATE VIEW v5 AS SELECT * FROM t1\;HAI 1.2 I HAS A t1 GIMMEH "id", id KTHXBYE\g

SELECT 1\;SELECT 2\;SELECT 3 \g
\d
