/*-------------------------------------------------------------------------
 *
 * compression.h
 *
 * Shared definitions for compression methods and specifications.
 *
 * Portions Copyright (c) 1996-2023, PostgreSQL Global Development Group
 *
 * IDENTIFICATION
 *		  src/include/common/compression.h
 *-------------------------------------------------------------------------
 */

#ifndef PG_COMPRESSION_H
#define PG_COMPRESSION_H

/*
 * These values are stored in disk, for example in files generated by pg_dump.
 * Create the necessary backwards compatibility layers if their order changes.
 * Make sure to keep COMPRESSION_ALGORITHM_COUNT in sync if adding new values.
 */
typedef enum pg_compress_algorithm
{
	PG_COMPRESSION_NONE,
	PG_COMPRESSION_GZIP,
	PG_COMPRESSION_LZ4,
	PG_COMPRESSION_ZSTD,
} pg_compress_algorithm;

#define COMPRESSION_ALGORITHM_COUNT		(PG_COMPRESSION_ZSTD + 1)

#define PG_COMPRESSION_OPTION_WORKERS		(1 << 0)
#define PG_COMPRESSION_OPTION_LONG_DISTANCE	(1 << 1)
#define PG_COMPRESSION_OPTION_COMPRESS		(1 << 2)
#define PG_COMPRESSION_OPTION_DECOMPRESS	(1 << 3)

typedef struct pg_compress_specification
{
	pg_compress_algorithm algorithm;
	unsigned	options;		/* OR of PG_COMPRESSION_OPTION constants */
	int			level;
	int			workers;
	bool		long_distance;
	bool		compress;
	bool		decompress;
	bool		has_error;
	char		parse_error[255];	/* Populated with error message if
									 * has_error is true */
} pg_compress_specification;

extern void parse_compress_options(const char *option, char **algorithm,
								   char **detail);
extern bool parse_compress_algorithm(char *name, pg_compress_algorithm *algorithm);
extern const char *get_compress_algorithm_name(pg_compress_algorithm algorithm);

extern void parse_compress_specification(pg_compress_algorithm algorithm,
										 char *specification,
										 pg_compress_specification *result,
										 unsigned allowed_options);
extern int	serialize_compress_specification(const pg_compress_specification *spec,
											 char *buffer,
											 size_t buffer_size);

extern char *validate_compress_specification(pg_compress_specification *);
extern bool supported_compression_algorithm(pg_compress_algorithm algorithm);

#endif
