#!/usr/bin/perl
#
# Generate a composition table and its lookup utilities, using Unicode data
# files as input.
#
# Input: UnicodeData.txt and CompositionExclusions.txt
# Output: unicode_norm_table.h
#
# Copyright (c) 2000-2026, PostgreSQL Global Development Group

use strict;
use warnings FATAL => 'all';
use Getopt::Long;

use FindBin;
use lib "$FindBin::RealBin/../../tools/";
use TwoStageTable;
use Text::Wrap;

$Text::Wrap::columns = 80;

my $output_path = '.';

GetOptions('outdir:s' => \$output_path);

my $output_table_file = "$output_path/unicode_norm_table.h";

my $FH;

# Read list of codes that should be excluded from re-composition.
my @composition_exclusion_codes = ();
open($FH, '<', "$output_path/CompositionExclusions.txt")
  or die "Could not open $output_path/CompositionExclusions.txt: $!.";
while (my $line = <$FH>)
{
	if ($line =~ /^([[:xdigit:]]+)/)
	{
		push @composition_exclusion_codes, $1;
	}
}
close $FH;

# Read entries from UnicodeData.txt into a list, and a hash table. We need
# three fields from each row: the codepoint, canonical combining class,
# and character decomposition mapping
my @characters = ();
my %character_hash = ();
open($FH, '<', "$output_path/UnicodeData.txt")
  or die "Could not open $output_path/UnicodeData.txt: $!.";
while (my $line = <$FH>)
{

	# Split the line wanted and get the fields needed:
	# - Unicode code value
	# - Canonical Combining Class
	# - Character Decomposition Mapping
	my @elts = split(';', $line);
	my $code = $elts[0];
	my $class = $elts[3];
	my $decomp = $elts[5];

	# Skip codepoints above U+10FFFF. They cannot be represented in 4 bytes
	# in UTF-8, and PostgreSQL doesn't support UTF-8 characters longer than
	# 4 bytes. (This is just pro forma, as there aren't any such entries in
	# the data file, currently.)
	next if hex($code) > 0x10FFFF;

	# The character decomposition mapping field in UnicodeData.txt is a list
	# of unicode codepoints, separated by space. But it can be prefixed with
	# so-called compatibility formatting tag, like "<compat>", or "<font>".
	# The entries with compatibility formatting tags should not be used for
	# re-composing characters during normalization, so flag them in the table.
	# (The tag doesn't matter, only whether there is a tag or not)
	my $compat = 0;
	if ($decomp =~ /\<.*\>/)
	{
		$compat = 1;
		$decomp =~ s/\<[^][]*\>//g;
	}
	my @decomp_elts = split(" ", $decomp);

	# Skip characters with no decompositions and a class of 0, to reduce the
	# table size.
	next if $class eq '0' && scalar @decomp_elts == 0;

	my %char_entry = (
		code => $code,
		class => $class,
		compat => $compat,
		decomp => \@decomp_elts,
		decomp_length => scalar @decomp_elts,
		canonical => [],
		compatibility => [],
		decomp_eq => 0);
	push(@characters, \%char_entry);
	$character_hash{ hex($code) } = \%char_entry;
}
close $FH;

# Start writing out the output files
open my $OT, '>', $output_table_file
  or die "Could not open output file $output_table_file: $!\n";

print $OT <<HEADER;
/*-------------------------------------------------------------------------
 *
 * unicode_norm_table.h
 *	  Composition table used for Unicode normalization
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * src/include/common/unicode_norm_table.h
 *
 *-------------------------------------------------------------------------
 */

/*
 * File auto-generated by src/common/unicode/generate-unicode_norm_table.pl,
 * do not edit. There is deliberately not an #ifndef PG_UNICODE_NORM_TABLE_H
 * here.
 */
typedef struct
{
	uint8		comb_class;		/* combining class of character */
	uint8		dec_size_flags; /* size and flags of decomposition code list */
	uint16		dec_index;		/* index into UnicodeDecompCodepoints, or the
								 * decomposition itself if DECOMP_INLINE */
} pg_unicode_decomposition;

#define DECOMP_NO_COMPOSE	0x80	/* don't use for re-composition */
#define DECOMP_INLINE		0x40	/* decomposition is stored inline in
									 * dec_index */
#define DECOMP_COMPAT		0x20	/* compatibility mapping */

#define DECOMPOSITION_SIZE(x) ((x)->dec_size_flags & 0x1F)
#define DECOMPOSITION_COMPAT_SIZE(x) (UnicodeDecompSizes[(x)->dec_index])
#define DECOMPOSITION_NO_COMPOSE(x) (((x)->dec_size_flags & (DECOMP_NO_COMPOSE | DECOMP_COMPAT)) != 0)
#define DECOMPOSITION_IS_INLINE(x) (((x)->dec_size_flags & DECOMP_INLINE) != 0)
#define DECOMPOSITION_IS_COMPAT(x) (((x)->dec_size_flags & DECOMP_COMPAT) != 0)

HEADER

# Sorting the values so that the table is always generated in the same way.
my @sorted_codes = sort { $a <=> $b } keys %character_hash;

foreach my $code (@sorted_codes)
{
	my $entry = $character_hash{$code};

	# Full Canonical Decomposition.
	$entry->{canonical} =
	  resolve_decomposition($entry->{decomp}, \%character_hash, 0);
	# Full Compatibility Decomposition.
	$entry->{compatibility} =
	  resolve_decomposition($entry->{decomp}, \%character_hash);
}

my @decomp_codepoints = (0);
my @compat_sizes = (0);

# Collect all codepoints of the decomposition and remove duplicate sequences.
# Be sure to sort by number of codepoints, from largest to smallest.
# This is necessary so that shorter ones fit into larger ones.
foreach my $code (
	sort {
		decomposition_sort_length($character_hash{$b})
		  <=> decomposition_sort_length($character_hash{$a})
		  || $a <=> $b
	} @sorted_codes)
{
	my $entry = $character_hash{$code};
	my $canonical = $entry->{canonical};
	my $compatibility = $entry->{compatibility};

	# Canonical and Compatibility have one index for the UnicodeDecompCodepoints
	# table. The difference is that different Canonical and Compatibility values
	# are written to the tables sequentially, the size from Canonical is
	# specified in UnicodeDecompMain, and the size from Compatibility is
	# specified in a separately created uint8 UnicodeDecompSizes table.
	#
	# That is, if we have an index from the UnicodeDecompMain table, the same
	# index will be suitable for obtaining the size from UnicodeDecompSizes.
	$entry->{decomp_eq} = arrays_equal($canonical, $compatibility);

	if (!$entry->{decomp_eq})
	{
		my $compat_size = scalar @$compatibility;
		my $index = scalar @decomp_codepoints;

		die "decomposition index for U+$entry->{code} does not fit in uint16"
		  if $index > 0xFFFF;
		die
		  "compatibility decomposition size for U+$entry->{code} does not fit in uint8"
		  if $compat_size > 0xFF;

		push @decomp_codepoints, @$canonical, @$compatibility;

		$compat_sizes[$index] = $compat_size;
		$entry->{decomp_index} = $index;

		next;
	}

	# Skip those values that will be stored directly in the main table.
	if (@$canonical == 0
		|| (@$canonical == 1 && length($canonical->[0]) <= 4))
	{
		next;
	}

	# Search for a sequence of decomposition codepoints in the existing data.
	# If found, we assign a record index; otherwise, we add the sequence to the
	# end of the existing data.
	my $index = contains_subarray(\@decomp_codepoints, $canonical);

	if ((exists $compat_sizes[$index] && $compat_sizes[$index])
		|| $index == -1)
	{
		$index = scalar @decomp_codepoints;

		die "decomposition index for U+$entry->{code} does not fit in uint16"
		  if $index > 0xFFFF;

		push @decomp_codepoints, @$canonical;
	}

	die "decomposition index for U+$entry->{code} does not fit in uint16"
	  if $index > 0xFFFF;

	$entry->{decomp_index} = $index;
	$compat_sizes[$index] = 0;
}

die "UnicodeDecompCodepoints table is too large for uint16 indexes"
  if scalar @decomp_codepoints > 0x10000;

my $main_index = 1;
my @decomp_main = ("\t{0, 0, 0},\n");
my %duplicates;
my %inverse;
my %decomp_index;
my $decomp_gsa = TwoStageTable->new(6);

my $last_code = $characters[-1]->{code};
foreach my $char (@characters)
{
	my $code = $char->{code};
	my $class = $char->{class};
	my $compat = $char->{compat};
	my $decomp = $char->{decomp};
	my $canonical = $char->{canonical};
	my $index = $char->{decomp_index};

	# Decomposition size
	# Print size of decomposition
	my $decomp_size = scalar(@$decomp);

	my $first_decomp = $decomp->[0];
	my $first_num = $first_decomp ? hex($first_decomp) : 0;
	my $first_canonical = $canonical->[0];

	my $flags = "";
	my $comment = "";

	if ($compat)
	{
		$flags .= " | DECOMP_COMPAT";
	}

	if ($decomp_size == 2)
	{
		# Should this be used for recomposition?
		if (   $character_hash{$first_num}
			&& $character_hash{$first_num}->{class} != 0)
		{
			$flags .= " | DECOMP_NO_COMPOSE";
			$comment = "non-starter decomposition";
		}
		else
		{
			foreach my $lcode (@composition_exclusion_codes)
			{
				if ($lcode eq $code)
				{
					$flags .= " | DECOMP_NO_COMPOSE";
					$comment = "in exclusion list";
					last;
				}
			}
		}

		# Save info for recomposeable codepoints.
		# Note that this MUST match the macro DECOMPOSITION_NO_COMPOSE in C
		# above!  See also the inverse lookup in recompose_code() found in
		# src/common/unicode_norm.c.
		if (!($flags =~ /DECOMP_COMPAT/ || $flags =~ /DECOMP_NO_COMPOSE/))
		{
			$inverse{$first_num}->{ hex($decomp->[1]) } = hex($code);
		}
	}

	my $line;
	$decomp_size = scalar @$canonical;
	die "canonical decomposition size for U+$code does not fit in bitmask"
	  if $decomp_size > 0x1F;
	die "decomposition index for U+$code does not fit in uint16"
	  if defined $index && $index > 0xFFFF;

	if (!$char->{decomp_eq})
	{
		$line = "\t{$class, $decomp_size$flags, $index}";
	}
	elsif ($decomp_size == 0)
	{
		$line = "\t{$class, 0$flags, 0}";
	}
	elsif ($decomp_size == 1 && hex($first_canonical) <= 0xFFFF)
	{

		# The decomposition consists of a single codepoint, and it fits
		# in a uint16, so we can store it "inline" in the main table.
		$flags .= " | DECOMP_INLINE";
		$line = "\t{$class, 1$flags, 0x$first_canonical}";
	}
	else
	{
		$line = "\t{$class, $decomp_size$flags, $index}";
	}

	$decomp_gsa->push(hex($code));

	# Check for duplicates and discard them.
	if (exists $duplicates{$line})
	{
		$decomp_index{ hex($code) } = $duplicates{$line};
		next;
	}

	die "UnicodeDecompMain index for U+$code does not fit in uint16"
	  if $main_index > 0xFFFF;

	$duplicates{$line} = $main_index;

	# We will satisfy pgindent.
	my $space = length($line) < 35 ? "\t" : " ";

	push @decomp_main, $line;

	# Push a comma after all items except the last one.
	push @decomp_main, "," unless ($code eq $last_code);
	push @decomp_main, "$space/* $comment */" if ($comment ne "");
	push @decomp_main, "\n" unless ($code eq $last_code);

	$decomp_index{ hex($code) } = $main_index++;
}

# Compile a table with sequences of codepoints for decomposition.
my @decomp_lines;

foreach my $index (0 .. $#decomp_codepoints)
{
	my $code = $decomp_codepoints[$index];
	push @decomp_lines, "0x$code";
}

# Сompile a table with sequences of sizes for full compatibility decomposition.
my @sizes_lines;

foreach my $index (0 .. $#compat_sizes)
{
	push @sizes_lines, $compat_sizes[$index] || 0;
}

# Preparing data for codepoint composition. A situation where two code points
# need to be converted into one (recomposition of the reordered Unicode string).
#
# For table with uint16 numbers.
# The first two entries are uint32 numbers - first second codepoint.
# The third entry indicates the number of elements immediately following
# this entry (third entry).
# For example:
#     {code, point, 3, 55, 64, 71, code, point, 2, 23, 45, code, point,...}
#
my %inverse_index;
my @inverse_second;
my @inverse_codes;
my $inverse_gsa = TwoStageTable->new(6);

# The reserved value for "not found", like a NULL.
push @inverse_second, 0, 0, 0;
push @inverse_codes, 0;

foreach my $first (sort { $a <=> $b } keys %inverse)
{
	my $seconds = $inverse{$first};
	my @sorted = sort { $a <=> $b } keys %$seconds;
	my $span = $sorted[-1] - $sorted[0];

	die "inverse table index for U+"
	  . sprintf("%04X", $first)
	  . " does not fit in uint16"
	  if scalar @inverse_second > 0xFFFF;
	die "inverse second-codepoint span for U+"
	  . sprintf("%04X", $first)
	  . " does not fit in uint16"
	  if $span > 0xFFFF;

	$inverse_index{$first} = scalar @inverse_second;
	$inverse_gsa->push($first);

	# Store a 32-bit number in two 16-bit numbers.
	push @inverse_second, $sorted[0] >> 16;
	push @inverse_second, $sorted[0] & 0xFFFF;
	# Store the number of entries.
	push @inverse_second, $span;

	foreach my $second ($sorted[0] .. $sorted[-1])
	{
		my $index = 0;

		if (exists $seconds->{$second})
		{
			$index = scalar @inverse_codes;
			die "inverse code index for U+"
			  . sprintf("%04X", $first)
			  . " does not fit in uint16"
			  if $index > 0xFFFF;
			push @inverse_codes, $seconds->{$second};
		}

		push @inverse_second, $index;
	}
}

die "UnicodeDecompInverseCodes table is too large for uint16 indexes"
  if scalar @inverse_codes > 0x10000;
die "UnicodeDecompInverseSecond table is too large for uint16 indexes"
  if scalar @inverse_second > 0x10000;

my $main_string = join "", @decomp_main;
my $decomp_length = scalar @decomp_lines;
my $decomp_string = wrap("\t", "\t", join(", ", @decomp_lines));
my $sizes_length = scalar @compat_sizes;
my $sizes_string = wrap("\t", "\t", join(", ", @sizes_lines));
my $inverse_length = scalar @inverse_codes;
my $inverse_string = wrap("\t", "\t", join(", ", @inverse_codes));
my $second_length = scalar @inverse_second;
my $second_string = wrap("\t", "\t", join(", ", @inverse_second));

die "the sizes of the UnicodeDecompCodepoints and UnicodeDecompSizes tables "
  . "do not match"
  if $decomp_length != $sizes_length;

# Print the array of decomposed codes.
print $OT <<HEADER;
/* Table with basic data for decompositions. */
static const pg_unicode_decomposition UnicodeDecompMain[$main_index] =
{
$main_string
};

/* Table with sequences of codepoints for decomposition. */
static const uint32 UnicodeDecompCodepoints[$decomp_length] =
{
$decomp_string
};

/*
 * Table of sizes for full compatibility decomposition.
 */
static const uint8 UnicodeDecompSizes[$sizes_length] =
{
$sizes_string
};

/*
 * Table of Unicode codepoints for recomposition of the reordered
 * Unicode string.
 */
static const uint32 UnicodeDecompInverseCodes[$inverse_length] =
{
$inverse_string
};

/*
 * Table with indexes from the secondary codepoint pointing
 * to UnicodeDecompInverseCodes.
 */
static const uint16 UnicodeDecompInverseSecond[$second_length] =
{
$second_string
};

HEADER

# Create index for decomposition mapping.
my ($decomp_table_offset, $decomp_table_index, $decomp_func) =
  $decomp_gsa->generate('decomp_table', 'normalization_index',
	sub { $decomp_index{ $_[0] } });

# Create index for inverse mapping.
my ($inverse_table_offset, $inverse_table_index, $inverse_func) =
  $inverse_gsa->generate('inverse_table', 'inverse_index',
	sub { $inverse_index{ $_[0] } });

print $OT <<"HEADER";
$decomp_table_offset

/*
 * Used by normalization_index() to map a codepoint to an index that can be
 * used in UnicodeDecompMain table.
 */
$decomp_table_index

$inverse_table_offset

/*
 * Used by inverse_index() to map a codepoint to an index that can be
 * used in UnicodeDecompInverseSecond table.
 */
$inverse_table_index

$decomp_func
$inverse_func
/*
 * normalization_inverse()
 *
 * Returns the code point for recomposition of the reordered Unicode string
 * based on two code points.
 * Codepoint 0x0000 means "not found".
 */
static char32_t
normalization_inverse(char32_t first, char32_t second)
{
	uint16		idx;
	uint32		start,
				stop;
	const uint16 *entry;

	idx = inverse_index(first);
	entry = &UnicodeDecompInverseSecond[idx];

	start = entry[0] << 16 | entry[1];
	stop = start + entry[2];

	if (idx != 0 && second >= start && second <= stop)
	{
		return UnicodeDecompInverseCodes[entry[second - start + 3]];
	}

	return 0x0000;
}
HEADER

close $OT;

# This function is designed to search for the occurrence of one array as
# a subarray within another.  This is necessary to find duplicates.
# It returns the index of the start of the occurrence or -1 if unsuccessful.
sub contains_subarray
{
	my ($arr1, $arr2) = @_;
	my $len1 = scalar(@$arr1);
	my $len2 = scalar(@$arr2);

	return -1 if $len2 == 0;
	return -1 if $len2 > $len1;

	for my $start (0 .. $len1 - $len2)
	{
		my $match = 1;

		for my $j (0 .. $len2 - 1)
		{
			if ($arr1->[ $start + $j ] ne $arr2->[$j])
			{
				$match = 0;
				last;
			}
		}

		return $start if $match;
	}

	return -1;
}

sub decomposition_sort_length
{
	my ($entry) = @_;
	my $canonical_length = scalar @{ $entry->{canonical} };
	my $compatibility_length = scalar @{ $entry->{compatibility} };

	return $canonical_length
	  if $canonical_length > $compatibility_length;
	return $compatibility_length;
}

sub resolve_decomposition
{
	my ($decomps, $index, $type) = @_;
	my ($res, @map);

	foreach my $cp (@$decomps)
	{
		my $entry = $index->{ hex($cp) };

		if (   defined $entry
			&& scalar @{ $entry->{decomp} }
			&& (!defined $type || $type == $entry->{compat}))
		{
			$res = resolve_decomposition($entry->{decomp}, $index, $type);
		}
		else
		{
			$res = [$cp];
		}

		push @map, @$res;
	}

	return \@map;
}

sub arrays_equal
{
	my ($arr1, $arr2) = @_;

	return 0 if @$arr1 != @$arr2;

	for my $i (0 .. $#$arr1)
	{
		return 0 if $arr1->[$i] ne $arr2->[$i];
	}

	return 1;
}
