#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/statmon
#
# IDENTIFICATION
#    src/backend/statmon/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/statmon
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = pgstat.o bestatus.o

include $(top_srcdir)/src/backend/common.mk
