#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/fdwxact
#
# IDENTIFICATION
#    src/backend/access/fdwxact/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/fdwxact
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	fdwxact.o \
	resolver.o \
	launcher.o

include $(top_srcdir)/src/backend/common.mk
