
# Copyright (c) 2021-2026, PostgreSQL Global Development Group

=pod

=head1 NAME

PostgreSQL::PGTypes - PostgreSQL backend type OID constants

=head1 SYNOPSIS

  use PostgreSQL::PGTypes;

  if ($type_oid == TEXTOID) { ... }

  if ($type_oid == INT4ARRAYOID) { ... }

=head1 DESCRIPTION

This module provides constants for PostgreSQL backend type OIDs, as defined
in C<src/include/catalog/pg_type_d.h>. These can be used to identify column
types in query results via C<PQftype()>.

All constants are exported by default.

=head1 EXPORTED CONSTANTS

=head2 Basic Types

C<BOOLOID>, C<BYTEAOID>, C<CHAROID>, C<NAMEOID>, C<INT8OID>, C<INT2OID>,
C<INT2VECTOROID>, C<INT4OID>, C<TEXTOID>, C<OIDOID>, C<TIDOID>, C<XIDOID>,
C<CIDOID>, C<OIDVECTOROID>, C<JSONOID>, C<XMLOID>, C<XID8OID>, C<POINTOID>,
C<LSEGOID>, C<PATHOID>, C<BOXOID>, C<POLYGONOID>, C<LINEOID>, C<FLOAT4OID>,
C<FLOAT8OID>, C<UNKNOWNOID>, C<CIRCLEOID>, C<MONEYOID>, C<MACADDROID>,
C<INETOID>, C<CIDROID>, C<MACADDR8OID>, C<ACLITEMOID>, C<BPCHAROID>,
C<VARCHAROID>, C<DATEOID>, C<TIMEOID>, C<TIMESTAMPOID>, C<TIMESTAMPTZOID>,
C<INTERVALOID>, C<TIMETZOID>, C<BITOID>, C<VARBITOID>, C<NUMERICOID>,
C<REFCURSOROID>, C<UUIDOID>, C<TSVECTOROID>, C<GTSVECTOROID>, C<TSQUERYOID>,
C<JSONBOID>, C<JSONPATHOID>, C<TXID_SNAPSHOTOID>

=head2 Range Types

C<INT4RANGEOID>, C<NUMRANGEOID>, C<TSRANGEOID>, C<TSTZRANGEOID>,
C<DATERANGEOID>, C<INT8RANGEOID>

=head2 Multirange Types

C<INT4MULTIRANGEOID>, C<NUMMULTIRANGEOID>, C<TSMULTIRANGEOID>,
C<TSTZMULTIRANGEOID>, C<DATEMULTIRANGEOID>, C<INT8MULTIRANGEOID>

=head2 Pseudo Types

C<RECORDOID>, C<RECORDARRAYOID>, C<CSTRINGOID>, C<VOIDOID>, C<TRIGGEROID>,
C<EVENT_TRIGGEROID>

=head2 Array Types

Array type OIDs follow the pattern C<{BASENAME}ARRAYOID>, e.g., C<TEXTARRAYOID>,
C<INT4ARRAYOID>, C<JSONBARRAYOID>.

=cut

package PostgreSQL::PGTypes;

use strict;
use warnings FATAL => qw(all);

use Exporter qw(import);

our @EXPORT = qw(

  BOOLOID
  BYTEAOID
  CHAROID
  NAMEOID
  INT8OID
  INT2OID
  INT2VECTOROID
  INT4OID
  TEXTOID
  OIDOID
  TIDOID
  XIDOID
  CIDOID
  OIDVECTOROID
  JSONOID
  XMLOID
  XID8OID
  POINTOID
  LSEGOID
  PATHOID
  BOXOID
  POLYGONOID
  LINEOID
  FLOAT4OID
  FLOAT8OID
  UNKNOWNOID
  CIRCLEOID
  MONEYOID
  MACADDROID
  INETOID
  CIDROID
  MACADDR8OID
  ACLITEMOID
  BPCHAROID
  VARCHAROID
  DATEOID
  TIMEOID
  TIMESTAMPOID
  TIMESTAMPTZOID
  INTERVALOID
  TIMETZOID
  BITOID
  VARBITOID
  NUMERICOID
  REFCURSOROID
  UUIDOID
  TSVECTOROID
  GTSVECTOROID
  TSQUERYOID
  JSONBOID
  JSONPATHOID
  TXID_SNAPSHOTOID
  INT4RANGEOID
  NUMRANGEOID
  TSRANGEOID
  TSTZRANGEOID
  DATERANGEOID
  INT8RANGEOID
  INT4MULTIRANGEOID
  NUMMULTIRANGEOID
  TSMULTIRANGEOID
  TSTZMULTIRANGEOID
  DATEMULTIRANGEOID
  INT8MULTIRANGEOID
  RECORDOID
  RECORDARRAYOID
  CSTRINGOID
  VOIDOID
  TRIGGEROID
  EVENT_TRIGGEROID

  BOOLARRAYOID
  BYTEAARRAYOID
  CHARARRAYOID
  NAMEARRAYOID
  INT8ARRAYOID
  INT2ARRAYOID
  INT2VECTORARRAYOID
  INT4ARRAYOID
  TEXTARRAYOID
  OIDARRAYOID
  TIDARRAYOID
  XIDARRAYOID
  CIDARRAYOID
  OIDVECTORARRAYOID
  JSONARRAYOID
  XMLARRAYOID
  XID8ARRAYOID
  POINTARRAYOID
  LSEGARRAYOID
  PATHARRAYOID
  BOXARRAYOID
  POLYGONARRAYOID
  LINEARRAYOID
  FLOAT4ARRAYOID
  FLOAT8ARRAYOID
  CIRCLEARRAYOID
  MONEYARRAYOID
  MACADDRARRAYOID
  INETARRAYOID
  CIDRARRAYOID
  MACADDR8ARRAYOID
  ACLITEMARRAYOID
  BPCHARARRAYOID
  VARCHARARRAYOID
  DATEARRAYOID
  TIMEARRAYOID
  TIMESTAMPARRAYOID
  TIMESTAMPTZARRAYOID
  INTERVALARRAYOID
  TIMETZARRAYOID
  BITARRAYOID
  VARBITARRAYOID
  NUMERICARRAYOID
  REFCURSORARRAYOID
  UUIDARRAYOID
  TSVECTORARRAYOID
  GTSVECTORARRAYOID
  TSQUERYARRAYOID
  JSONBARRAYOID
  JSONPATHARRAYOID
  TXID_SNAPSHOTARRAYOID
  INT4RANGEARRAYOID
  NUMRANGEARRAYOID
  TSRANGEARRAYOID
  TSTZRANGEARRAYOID
  DATERANGEARRAYOID
  INT8RANGEARRAYOID
  INT4MULTIRANGEARRAYOID
  NUMMULTIRANGEARRAYOID
  TSMULTIRANGEARRAYOID
  TSTZMULTIRANGEARRAYOID
  DATEMULTIRANGEARRAYOID
  INT8MULTIRANGEARRAYOID
  CSTRINGARRAYOID

);

use constant {
	BOOLOID                 => 16,
	BYTEAOID                => 17,
	CHAROID                 => 18,
	NAMEOID                 => 19,
	INT8OID                 => 20,
	INT2OID                 => 21,
	INT2VECTOROID           => 22,
	INT4OID                 => 23,
	TEXTOID                 => 25,
	OIDOID                  => 26,
	TIDOID                  => 27,
	XIDOID                  => 28,
	CIDOID                  => 29,
	OIDVECTOROID            => 30,
	JSONOID                 => 114,
	XMLOID                  => 142,
	XID8OID                 => 5069,
	POINTOID                => 600,
	LSEGOID                 => 601,
	PATHOID                 => 602,
	BOXOID                  => 603,
	POLYGONOID              => 604,
	LINEOID                 => 628,
	FLOAT4OID               => 700,
	FLOAT8OID               => 701,
	UNKNOWNOID              => 705,
	CIRCLEOID               => 718,
	MONEYOID                => 790,
	MACADDROID              => 829,
	INETOID                 => 869,
	CIDROID                 => 650,
	MACADDR8OID             => 774,
	ACLITEMOID              => 1033,
	BPCHAROID               => 1042,
	VARCHAROID              => 1043,
	DATEOID                 => 1082,
	TIMEOID                 => 1083,
	TIMESTAMPOID            => 1114,
	TIMESTAMPTZOID          => 1184,
	INTERVALOID             => 1186,
	TIMETZOID               => 1266,
	BITOID                  => 1560,
	VARBITOID               => 1562,
	NUMERICOID              => 1700,
	REFCURSOROID            => 1790,
	UUIDOID                 => 2950,
	TSVECTOROID             => 3614,
	GTSVECTOROID            => 3642,
	TSQUERYOID              => 3615,
	JSONBOID                => 3802,
	JSONPATHOID             => 4072,
	TXID_SNAPSHOTOID        => 2970,
	INT4RANGEOID            => 3904,
	NUMRANGEOID             => 3906,
	TSRANGEOID              => 3908,
	TSTZRANGEOID            => 3910,
	DATERANGEOID            => 3912,
	INT8RANGEOID            => 3926,
	INT4MULTIRANGEOID       => 4451,
	NUMMULTIRANGEOID        => 4532,
	TSMULTIRANGEOID         => 4533,
	TSTZMULTIRANGEOID       => 4534,
	DATEMULTIRANGEOID       => 4535,
	INT8MULTIRANGEOID       => 4536,
	RECORDOID               => 2249,
	RECORDARRAYOID          => 2287,
	CSTRINGOID              => 2275,
	VOIDOID                 => 2278,
	TRIGGEROID              => 2279,
	EVENT_TRIGGEROID        => 3838,

	BOOLARRAYOID            => 1000,
	BYTEAARRAYOID           => 1001,
	CHARARRAYOID            => 1002,
	NAMEARRAYOID            => 1003,
	INT8ARRAYOID            => 1016,
	INT2ARRAYOID            => 1005,
	INT2VECTORARRAYOID      => 1006,
	INT4ARRAYOID            => 1007,
	TEXTARRAYOID            => 1009,
	OIDARRAYOID             => 1028,
	TIDARRAYOID             => 1010,
	XIDARRAYOID             => 1011,
	CIDARRAYOID             => 1012,
	OIDVECTORARRAYOID       => 1013,
	JSONARRAYOID            => 199,
	XMLARRAYOID             => 143,
	XID8ARRAYOID            => 271,
	POINTARRAYOID           => 1017,
	LSEGARRAYOID            => 1018,
	PATHARRAYOID            => 1019,
	BOXARRAYOID             => 1020,
	POLYGONARRAYOID         => 1027,
	LINEARRAYOID            => 629,
	FLOAT4ARRAYOID          => 1021,
	FLOAT8ARRAYOID          => 1022,
	CIRCLEARRAYOID          => 719,
	MONEYARRAYOID           => 791,
	MACADDRARRAYOID         => 1040,
	INETARRAYOID            => 1041,
	CIDRARRAYOID            => 651,
	MACADDR8ARRAYOID        => 775,
	ACLITEMARRAYOID         => 1034,
	BPCHARARRAYOID          => 1014,
	VARCHARARRAYOID         => 1015,
	DATEARRAYOID            => 1182,
	TIMEARRAYOID            => 1183,
	TIMESTAMPARRAYOID       => 1115,
	TIMESTAMPTZARRAYOID     => 1185,
	INTERVALARRAYOID        => 1187,
	TIMETZARRAYOID          => 1270,
	BITARRAYOID             => 1561,
	VARBITARRAYOID          => 1563,
	NUMERICARRAYOID         => 1231,
	REFCURSORARRAYOID       => 2201,
	UUIDARRAYOID            => 2951,
	TSVECTORARRAYOID        => 3643,
	GTSVECTORARRAYOID       => 3644,
	TSQUERYARRAYOID         => 3645,
	JSONBARRAYOID           => 3807,
	JSONPATHARRAYOID        => 4073,
	TXID_SNAPSHOTARRAYOID   => 2949,
	INT4RANGEARRAYOID       => 3905,
	NUMRANGEARRAYOID        => 3907,
	TSRANGEARRAYOID         => 3909,
	TSTZRANGEARRAYOID       => 3911,
	DATERANGEARRAYOID       => 3913,
	INT8RANGEARRAYOID       => 3927,
	INT4MULTIRANGEARRAYOID  => 6150,
	NUMMULTIRANGEARRAYOID   => 6151,
	TSMULTIRANGEARRAYOID    => 6152,
	TSTZMULTIRANGEARRAYOID  => 6153,
	DATEMULTIRANGEARRAYOID  => 6155,
	INT8MULTIRANGEARRAYOID  => 6157,
	CSTRINGARRAYOID         => 1263,
};

=pod

=head1 SEE ALSO

L<PostgreSQL::PqFFI>, L<PostgreSQL::Test::Session>

=cut

1;
