
# Copyright (c) 2021-2026, PostgreSQL Global Development Group

=pod

=head1 NAME

PostgreSQL::PqConstants - libpq constants for PostgreSQL TAP tests

=head1 SYNOPSIS

  use PostgreSQL::PqConstants;

  if (PQstatus($conn) == CONNECTION_OK) { ... }

  if (PQresultStatus($result) == PGRES_TUPLES_OK) { ... }

=head1 DESCRIPTION

This module provides libpq constants used by the FFI backend
(C<PostgreSQL::PqFFI>).  All constants are exported by default.

=head1 EXPORTED CONSTANTS

=head2 Connection Status (ConnStatusType)

C<CONNECTION_OK>, C<CONNECTION_BAD>, C<CONNECTION_STARTED>,
C<CONNECTION_MADE>, C<CONNECTION_AWAITING_RESPONSE>, C<CONNECTION_AUTH_OK>,
C<CONNECTION_SETENV>, C<CONNECTION_SSL_STARTUP>, C<CONNECTION_NEEDED>,
C<CONNECTION_CHECK_WRITABLE>, C<CONNECTION_CONSUME>, C<CONNECTION_GSS_STARTUP>,
C<CONNECTION_CHECK_TARGET>, C<CONNECTION_CHECK_STANDBY>, C<CONNECTION_ALLOCATED>

=head2 Execution Status (ExecStatusType)

C<PGRES_EMPTY_QUERY>, C<PGRES_COMMAND_OK>, C<PGRES_TUPLES_OK>,
C<PGRES_COPY_OUT>, C<PGRES_COPY_IN>, C<PGRES_BAD_RESPONSE>,
C<PGRES_NONFATAL_ERROR>, C<PGRES_FATAL_ERROR>, C<PGRES_COPY_BOTH>,
C<PGRES_SINGLE_TUPLE>, C<PGRES_PIPELINE_SYNC>, C<PGRES_PIPELINE_ABORTED>,
C<PGRES_TUPLES_CHUNK>

=head2 Polling Status (PostgresPollingStatusType)

C<PGRES_POLLING_FAILED>, C<PGRES_POLLING_READING>, C<PGRES_POLLING_WRITING>,
C<PGRES_POLLING_OK>, C<PGRES_POLLING_ACTIVE>

=head2 Ping Status (PGPing)

C<PQPING_OK>, C<PQPING_REJECT>, C<PQPING_NO_RESPONSE>, C<PQPING_NO_ATTEMPT>

=head2 Transaction Status (PGTransactionStatusType)

C<PQTRANS_IDLE>, C<PQTRANS_ACTIVE>, C<PQTRANS_INTRANS>, C<PQTRANS_INERROR>,
C<PQTRANS_UNKNOWN>

=cut

package PostgreSQL::PqConstants;

use strict;
use warnings FATAL => qw(all);

use Exporter qw(import);

our @EXPORT = qw(

  CONNECTION_OK
  CONNECTION_BAD
  CONNECTION_STARTED
  CONNECTION_MADE
  CONNECTION_AWAITING_RESPONSE
  CONNECTION_AUTH_OK
  CONNECTION_SETENV
  CONNECTION_SSL_STARTUP
  CONNECTION_NEEDED
  CONNECTION_CHECK_WRITABLE
  CONNECTION_CONSUME
  CONNECTION_GSS_STARTUP
  CONNECTION_CHECK_TARGET
  CONNECTION_CHECK_STANDBY
  CONNECTION_ALLOCATED

  PGRES_EMPTY_QUERY
  PGRES_COMMAND_OK
  PGRES_TUPLES_OK
  PGRES_COPY_OUT
  PGRES_COPY_IN
  PGRES_BAD_RESPONSE
  PGRES_NONFATAL_ERROR
  PGRES_FATAL_ERROR
  PGRES_COPY_BOTH
  PGRES_SINGLE_TUPLE
  PGRES_PIPELINE_SYNC
  PGRES_PIPELINE_ABORTED
  PGRES_TUPLES_CHUNK

  PGRES_POLLING_FAILED
  PGRES_POLLING_READING
  PGRES_POLLING_WRITING
  PGRES_POLLING_OK
  PGRES_POLLING_ACTIVE

  PQPING_OK
  PQPING_REJECT
  PQPING_NO_RESPONSE
  PQPING_NO_ATTEMPT

  PQTRANS_IDLE
  PQTRANS_ACTIVE
  PQTRANS_INTRANS
  PQTRANS_INERROR
  PQTRANS_UNKNOWN

);

# ConnStatusType:
use constant {
	CONNECTION_OK                 => 0,
	CONNECTION_BAD                => 1,
	CONNECTION_STARTED            => 2,
	CONNECTION_MADE               => 3,
	CONNECTION_AWAITING_RESPONSE  => 4,
	CONNECTION_AUTH_OK            => 5,
	CONNECTION_SETENV             => 6,
	CONNECTION_SSL_STARTUP        => 7,
	CONNECTION_NEEDED             => 8,
	CONNECTION_CHECK_WRITABLE     => 9,
	CONNECTION_CONSUME            => 10,
	CONNECTION_GSS_STARTUP        => 11,
	CONNECTION_CHECK_TARGET       => 12,
	CONNECTION_CHECK_STANDBY      => 13,
	CONNECTION_ALLOCATED          => 14,
};

# ExecStatusType:
use constant {
	PGRES_EMPTY_QUERY     => 0,
	PGRES_COMMAND_OK      => 1,
	PGRES_TUPLES_OK       => 2,
	PGRES_COPY_OUT        => 3,
	PGRES_COPY_IN         => 4,
	PGRES_BAD_RESPONSE    => 5,
	PGRES_NONFATAL_ERROR  => 6,
	PGRES_FATAL_ERROR     => 7,
	PGRES_COPY_BOTH       => 8,
	PGRES_SINGLE_TUPLE    => 9,
	PGRES_PIPELINE_SYNC   => 10,
	PGRES_PIPELINE_ABORTED => 11,
	PGRES_TUPLES_CHUNK    => 12,
};

# PostgresPollingStatusType:
use constant {
	PGRES_POLLING_FAILED  => 0,
	PGRES_POLLING_READING => 1,
	PGRES_POLLING_WRITING => 2,
	PGRES_POLLING_OK      => 3,
	PGRES_POLLING_ACTIVE  => 4,
};

# PGPing:
use constant {
	PQPING_OK          => 0,
	PQPING_REJECT      => 1,
	PQPING_NO_RESPONSE => 2,
	PQPING_NO_ATTEMPT  => 3,
};

# PGTransactionStatusType:
use constant {
	PQTRANS_IDLE    => 0,
	PQTRANS_ACTIVE  => 1,
	PQTRANS_INTRANS => 2,
	PQTRANS_INERROR => 3,
	PQTRANS_UNKNOWN => 4,
};

=pod

=head1 SEE ALSO

L<PostgreSQL::PqFFI>, L<PostgreSQL::Test::Session>

=cut

1;
