#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/restore
#
# IDENTIFICATION
#    src/backend/restore/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/restore
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	shell_restore.o

include $(top_srcdir)/src/backend/common.mk
