#!/usr/bin/perl

# Copyright (c) 2021-2026, PostgreSQL Global Development Group

# Unified tool for formatting and checking PostgreSQL C and Perl code.
#
# Supported tools
#   --pgindent       format C code with pg_bsd_indent
#   --perltidy       format Perl code with perltidy
#   --perlcritic     lint Perl code with perlcritic
#   --perl-syncheck  syntax-check Perl code with perl -cw
#
# When no tool flags are given, all tools are run.
#
# Exit codes:
#   0 -- all OK
#   1 -- error invoking pgcheck, nothing done
#   2 -- --check mode and at least one file requires changes
#   3 -- a formatting or checking tool failed on at least one file

use strict;
use warnings FATAL => 'all';

use Cwd qw(abs_path getcwd);
use File::Spec;
use File::Temp;
use IO::Handle;
use Getopt::Long;
use Fcntl qw(:flock);

# By default Perl's SIGINT/SIGTERM kill the process without running
# END blocks, so File::Temp never gets to clean up.  Converting the
# signal into an exit() makes END-block cleanup run.  See:
# <http://www.perlmonks.org/?node_id=714225>.  Exit codes use the
# 128+signum convention so callers can tell the process was killed by
# a signal.
$SIG{INT} = sub { exit 130; };     # 128 + 2 (SIGINT)
$SIG{TERM} = sub { exit 143; };    # 128 + 15 (SIGTERM)

# pg_bsd_indent creates a .BAK file that File::Temp doesn't know about. This
# END block makes sure that that file is cleaned up in case someone presses
# Ctrl+C during pgindent.
my $bak_to_cleanup;
END { unlink $bak_to_cleanup if defined $bak_to_cleanup; }

# Update for pg_bsd_indent version
my $INDENT_VERSION = "2.1.3";

# Our standard indent settings
my $indent_opts =
  "-bad -bap -bbb -bc -bl -cli1 -cp33 -cdb -nce -d0 -di12 -nfc1 -i4 -l79 -lp -lpl -nip -npro -sac -tpg -ts4";

my $devnull = File::Spec->devnull;

my ($typedefs_file, $typedef_str, @excludes, $indent,
	$diff, $check, $help, @commits,
	$perltidy_arg, $perlcritic_arg, $jobs,);

# tool selectors
my ($do_pgindent, $do_perltidy, $do_perlcritic, $do_perl_syncheck);

$help = 0;
$jobs = 0;

# Save @ARGV before parsing so we can distinguish --perltidy=PATH (where
# the value should be used as the perltidy path) from --perltidy PATH
# (where PATH is a file to format that Getopt::Long greedily consumed).
# Same for --perlcritic.
my @orig_argv = @ARGV;

my %options = (
	"help" => \$help,
	"commit=s" => \@commits,
	"typedefs=s" => \$typedefs_file,
	"list-of-typedefs=s" => \$typedef_str,
	"excludes=s" => \@excludes,
	"indent=s" => \$indent,
	"pgindent" => \$do_pgindent,
	"perltidy:s" => \$perltidy_arg,
	"perlcritic:s" => \$perlcritic_arg,
	"perl-syncheck" => \$do_perl_syncheck,
	"diff" => \$diff,
	"check" => \$check,
	"jobs|j=i" => \$jobs,);
GetOptions(%options) || usage("bad command line argument");

if ($jobs == 0)
{
	$jobs = get_num_cpus();
}
elsif ($jobs < 0)
{
	usage("--jobs must be a non-negative number");
}

# For --perltidy and --perlcritic, distinguish =PATH from bare PATH. The PATH
# in =PATH is interpreted as a path to the perltidy/perlcritic binary, but a
# separated PATH is interpreted as a file to be processed.
foreach my $pair ([ \$perltidy_arg, "perltidy" ],
	[ \$perlcritic_arg, "perlcritic" ])
{
	my ($ref, $name) = @$pair;
	if (defined($$ref) && $$ref ne '')
	{
		unless (grep { $_ eq "--$name=$$ref" } @orig_argv)
		{
			# If it's not =PATH add the argument back to @ARGV for processing
			# as a file argument
			unshift(@ARGV, $$ref);
			# Set the $perltidy_arg/perlcritic_arg to the empty string, to
			# indicate for the later code that the tool was selected but no
			# path was given.
			$$ref = '';
		}
	}
}

# --perltidy and --perlcritic as tool selectors: if given (even
# without a value), they select their respective tool.
$do_perltidy = 1 if defined($perltidy_arg);
$do_perlcritic = 1 if defined($perlcritic_arg);

usage() if $help;

usage("Cannot use --commit with command line file list")
  if (@commits && @ARGV);

# default to current directory if no files/dirs given
@ARGV = ('.') unless @ARGV || @commits;

# If no tool flags were given, run everything.
my $any_op =
	 $do_pgindent
  || $do_perltidy
  || $do_perlcritic
  || $do_perl_syncheck;
if (!$any_op)
{
	$do_pgindent = 1;
	$do_perltidy = 1;
	$do_perlcritic = 1;
	$do_perl_syncheck = 1;
}

my $do_perl_any = $do_perltidy || $do_perlcritic || $do_perl_syncheck;

# command line option wins, then environment, then locations based on current
# dir, then default location
$typedefs_file ||= $ENV{PGTYPEDEFS};

my $sourcedir = locate_sourcedir();

# get indent location: command line wins, then environment, then try to find
# a compiled pg_bsd_indent in the source tree, then fall back to PATH.
$indent ||= $ENV{PGINDENT} || $ENV{INDENT};
if (!$indent && $sourcedir)
{
	my $srcroot = "$sourcedir/../../..";
	my $bsd_indent_subdir = "src/tools/pg_bsd_indent/pg_bsd_indent";

	# Look for pg_bsd_indent: first in-tree (autoconf in-tree build),
	# then in a "build" directory (meson or autoconf vpath),
	# then any "build*" directory.
	foreach my $candidate (
		"$srcroot/$bsd_indent_subdir",
		"$srcroot/build/$bsd_indent_subdir",
		glob("$srcroot/build*/$bsd_indent_subdir"))
	{
		if (-x $candidate)
		{
			$indent = $candidate;
			last;
		}
	}
}
$indent ||= "pg_bsd_indent";

# get perltidy location: command line wins, then environment, then PATH.
my $perltidy = $perltidy_arg || $ENV{PERLTIDY} || "perltidy";

# get perlcritic location: command line wins, then environment, then PATH.
my $perlcritic = $perlcritic_arg || $ENV{PERLCRITIC} || "perlcritic";

# if it's the base of a postgres tree, we will exclude the files
# postgres wants excluded
if ($sourcedir)
{
	my $exclude_candidate = "$sourcedir/exclude_file_patterns";
	push(@excludes, $exclude_candidate) if -f $exclude_candidate;
}

# The typedef list that's mechanically extracted by the buildfarm may omit
# some names we want to treat like typedefs, e.g. "bool" (which is a macro
# according to <stdbool.h>), and may include some names we don't want
# treated as typedefs, although various headers that some builds include
# might make them so.  For the moment we just hardwire a list of names
# to add and a list of names to exclude; eventually this may need to be
# easier to configure.  Note that the typedefs need trailing newlines.
my @additional = map { "$_\n" } qw(
  bool regex_t regmatch_t regoff
);

my %excluded = map { +"$_\n" => 1 } qw(
  FD_SET LookupSet boolean date duration
  element_type inquiry iterator other
  pointer reference rep string timestamp type wrap
);

# globals
my @files;
my $filtered_typedefs_fh;
my $stdout_lock_fh;

sub get_num_cpus
{
	# Try nproc (Linux, some BSDs), then sysctl (macOS, FreeBSD).
	for my $cmd ('nproc', 'sysctl -n hw.ncpu')
	{
		my $n = `$cmd 2>$devnull`;
		chomp $n;
		return $n + 0 if ($? == 0 && $n =~ /^\d+$/ && $n > 0);
	}
	return 1;
}

sub check_indent
{
	if (system("$indent -? < $devnull > $devnull 2>&1") != 0)
	{
		if ($? >> 8 != 1)
		{
			print STDERR
			  "You do not appear to have $indent installed on your system.\n";
			exit 1;
		}
	}

	if (`$indent --version` !~ m/ $INDENT_VERSION /)
	{
		print STDERR
		  "You do not appear to have $indent version $INDENT_VERSION installed on your system.\n";
		exit 1;
	}

	if (system("$indent -gnu < $devnull > $devnull 2>&1") == 0)
	{
		print STDERR
		  "You appear to have GNU indent rather than BSD indent.\n";
		exit 1;
	}

	return;
}

my $PERLTIDY_VERSION = "20230309";

sub check_perltidy
{
	if (!$sourcedir)
	{
		print STDERR
		  "Cannot find perltidyrc: not running inside a PostgreSQL source tree.\n";
		exit 1;
	}

	my $ver = `$perltidy -v 2>&1`;
	if ($? != 0)
	{
		print STDERR
		  "You do not appear to have $perltidy installed on your system.\n"
		  . "See src/tools/pgindent/README for installation instructions.\n";
		exit 1;
	}

	if ($ver !~ m/$PERLTIDY_VERSION/)
	{
		print STDERR
		  "You do not appear to have $perltidy version $PERLTIDY_VERSION installed on your system.\n"
		  . "See src/tools/pgindent/README for installation instructions.\n";
		exit 1;
	}

	return;
}

sub check_perlcritic
{
	if (!$sourcedir)
	{
		print STDERR
		  "Cannot find perlcriticrc: not running inside a PostgreSQL source tree.\n";
		exit 1;
	}

	my $ver = `$perlcritic --version 2>&1`;
	if ($? != 0)
	{
		print STDERR
		  "You do not appear to have $perlcritic installed on your system.\n";
		exit 1;
	}

	return;
}

sub locate_sourcedir
{
	# try fairly hard to locate the sourcedir
	my $sub = "./src/tools/pgindent";
	return $sub if -d $sub;
	# try to find it from an ancestor directory
	$sub = "../src/tools/pgindent";
	foreach (1 .. 4)
	{
		return $sub if -d $sub;
		$sub = "../$sub";
	}
	return;    # undef if nothing found
}

sub load_typedefs
{
	# try fairly hard to find the typedefs file if it's not set

	foreach my $try ('.', $sourcedir, '/usr/local/etc')
	{
		last if $typedefs_file;
		next unless defined $try;
		$typedefs_file = "$try/typedefs.list"
		  if (-f "$try/typedefs.list");
	}

	die "cannot locate typedefs file \"$typedefs_file\"\n"
	  unless $typedefs_file && -f $typedefs_file;

	open(my $typedefs_fh, '<', $typedefs_file)
	  || die "cannot open typedefs file \"$typedefs_file\": $!\n";
	my @typedefs = <$typedefs_fh>;
	close($typedefs_fh);

	# add command-line-supplied typedefs?
	if (defined($typedef_str))
	{
		foreach my $typedef (split(m/[, \t\n]+/, $typedef_str))
		{
			push(@typedefs, $typedef . "\n");
		}
	}

	# add additional entries
	push(@typedefs, @additional);

	# remove excluded entries
	@typedefs = grep { !$excluded{$_} } @typedefs;

	# write filtered typedefs
	my $filter_typedefs_fh = new File::Temp(TEMPLATE => "pgtypedefXXXXX");
	print $filter_typedefs_fh @typedefs;
	$filter_typedefs_fh->close();

	# temp file remains because we return a file handle reference
	return $filter_typedefs_fh;
}

sub process_exclude
{
	foreach my $excl (@excludes)
	{
		last unless @files;
		open(my $eh, '<', $excl)
		  || die "cannot open exclude file \"$excl\"\n";
		while (my $line = <$eh>)
		{
			chomp $line;
			next if $line =~ m/^#/ || $line eq "";
			my $rgx = qr!$line!;
			@files = grep { $_ !~ /$rgx/ } @files if $rgx;
		}
		close($eh);
	}
	return;
}

sub read_source
{
	my $source_filename = shift;
	my $source;

	open(my $src_fd, '<', $source_filename)
	  || die "cannot open file \"$source_filename\": $!\n";
	local ($/) = undef;
	$source = <$src_fd>;
	close($src_fd);

	return $source;
}

sub write_source
{
	my $source = shift;
	my $source_filename = shift;

	open(my $src_fh, '>', $source_filename)
	  || die "cannot open file \"$source_filename\": $!\n";
	print $src_fh $source;
	close($src_fh);
	return;
}

sub pre_indent
{
	my $source = shift;

	## Ensure file ends with a newline (pg_bsd_indent messes up otherwise)
	$source .= "\n" unless substr($source, -1) eq "\n";

	## Comments

	# Convert // comments to /* */
	$source =~ s!^([ \t]*)//(.*)$!$1/* $2 */!gm;

	# Adjust dash-protected block comments so indent won't change them
	$source =~ s!/\* +---!/*---X_X!g;

	## Other

	# Prevent indenting of code in 'extern "C"' blocks.
	# we replace the braces with comments which we'll reverse later
	my $extern_c_start = '/* Open extern "C" */';
	my $extern_c_stop = '/* Close extern "C" */';
	$source =~
	  s!(^#ifdef[ \t]+__cplusplus.*\nextern[ \t]+"C"[ \t]*\n)\{[ \t]*$!$1$extern_c_start!gm;
	$source =~ s!(^#ifdef[ \t]+__cplusplus.*\n)\}[ \t]*$!$1$extern_c_stop!gm;

	# Protect wrapping in CATALOG()
	$source =~ s!^(CATALOG\(.*)$!/*$1*/!gm;

	return $source;
}

sub post_indent
{
	my $source = shift;

	# Restore CATALOG lines
	$source =~ s!^/\*(CATALOG\(.*)\*/$!$1!gm;

	# Put back braces for extern "C"
	$source =~ s!^/\* Open extern "C" \*/$!{!gm;
	$source =~ s!^/\* Close extern "C" \*/$!}!gm;

	## Comments

	# Undo change of dash-protected block comments
	$source =~ s!/\*---X_X!/* ---!g;

	# Fix run-together comments to have a tab between them
	$source =~ s!\*/(/\*.*\*/)$!*/\t$1!gm;

	# Postprocess multiline comments except for /**... and /*-... ones
	$source =~ s!^(/\*[^\*\-].*?\*/)!postprocess_multiline_comment($1)!mgse;

	## Functions

	# Use a single space before '*' in function return types
	$source =~ s!^([A-Za-z_]\S*)[ \t]+\*$!$1 *!gm;

	return $source;
}

sub postprocess_multiline_comment
{
	my $source = shift;
	my @lines = split "\n", $source;

	# Only reformat comments that actually span more than one line
	if (scalar @lines < 2)
	{
		return $source;
	}

	# Split any text on the first line onto a separate line,
	# but keep /* === and /* --- lines as is
	if ($lines[0] !~ m!^/\*\s+[=-]+$!)
	{
		$lines[0] =~ s!/\*\s*(.+)!/\*\n * $1!;
	}

	# Apply these steps to all lines but the first
	for my $i (1 .. scalar @lines - 1)
	{
		# Insert ' * ' if first non-white-space character is not '*'
		$lines[$i] =~ s/^\s*/ \* / if $lines[$i] !~ /^\s*\*/;
		# ... but that might leave us with trailing space
		$lines[$i] =~ s/\s+$//;
		# Require exactly one leading '*', and one space before it
		$lines[$i] =~ s/^\s*\*+/ \*/;
	}

	# Split trailing "*/" onto its own line if not that already,
	# but keep === */ and --- */ lines as is
	if ($lines[-1] !~ m!^\s*[=-]+\s+\*/$!)
	{
		# this also removes any trailing whitespace
		$lines[-1] =~ s!(.+?)\s+\*/!$1\n \*/!;
	}

	$source = join "\n", @lines;

	return $source;
}

sub run_indent
{
	my $source = shift;
	my $error_message = shift;

	my $cmd = "$indent $indent_opts -U" . $filtered_typedefs_fh->filename;

	my $tmp_fh = new File::Temp(TEMPLATE => "pgsrcXXXXX");
	my $filename = $tmp_fh->filename;
	print $tmp_fh $source;
	$tmp_fh->close();

	$bak_to_cleanup = "$filename.BAK";

	$$error_message = `$cmd $filename 2>&1`;

	return "" if ($? || length($$error_message) > 0);

	unlink $bak_to_cleanup;
	$bak_to_cleanup = undef;

	open(my $src_out, '<', $filename) || die $!;
	local ($/) = undef;
	$source = <$src_out>;
	close($src_out);

	return $source;
}

sub format_c
{
	my $source = shift;
	my $source_filename = shift;
	my $error_message = '';

	my $formatted = pre_indent($source);
	$formatted = run_indent($formatted, \$error_message);
	if ($formatted eq "")
	{
		print "Failure in $source_filename: " . $error_message . "\n";
		return ("", 1);
	}
	return post_indent($formatted);
}

sub format_perl
{
	my $source = shift;
	my $source_filename = shift;

	my $tmp_fh = new File::Temp(TEMPLATE => "pgperltidyXXXXX");
	my $tmp_filename = $tmp_fh->filename;
	print $tmp_fh $source;
	$tmp_fh->close();

	my $perltidy_profile = "$sourcedir/perltidyrc";
	my $err =
	  `$perltidy --profile=$perltidy_profile -b -bext='/' $tmp_filename 2>&1`;
	if ($? != 0)
	{
		print "Failure in $source_filename: " . $err . "\n";
		return ("", 1);
	}
	return read_source($tmp_filename);
}

sub run_perlcritic
{
	my $source_filename = shift;

	my $perlcheck_dir = "$sourcedir/../perlcheck";
	my $criticrc = "$perlcheck_dir/perlcriticrc";

	my $err =
	  `$perlcritic --quiet --program-extensions .pl --profile=$criticrc "$source_filename" 2>&1`;
	return ("", 0) if $? == 0;
	return ($err, 1);
}

sub run_perl_syncheck
{
	my $source_filename = shift;

	my $includes = join(
		' ',
		map { "-I $_" } (
			"src/backend/catalog", "src/test/perl",
			"src/backend/utils/mb/Unicode", "src/bin/pg_rewind",
			"src/test/ssl/t",));

	my $output = `perl $includes -cw "$source_filename" 2>&1`;
	my $failed = $? != 0;

	# Filter out "OK" lines — perl -cw prints "<file> syntax OK" on success
	my @lines = grep { !/\bsyntax OK$/ } split(/\n/, $output);
	my $filtered = join("\n", @lines);
	$filtered .= "\n" if $filtered;

	return ($filtered, $failed || scalar(@lines) > 0);
}

sub diff
{
	my $indented = shift;
	my $source_filename = shift;

	my $post_fh = new File::Temp(TEMPLATE => "pgdiffXXXXX");
	my $post_fh_filename = $post_fh->filename;

	print $post_fh $indented;

	$post_fh->close();

	my $diff = `diff -upd "$source_filename" "$post_fh_filename"  2>&1`;
	return $diff;
}

sub is_c_file
{
	my $filename = shift;
	# It needs to have .c or .h extension
	return 0 unless $filename =~ /\.[ch]$/;
	# Automatically ignore .c and .h files that correspond to a .y or .l file.
	# pg_bsd_indent tends to get badly confused by Bison/flex output, and
	# there's no value in indenting derived files anyway.
	my $otherfile = $filename;
	$otherfile =~ s/\.[ch]$/.y/;
	return 0 if $otherfile ne $filename && -f $otherfile;
	$otherfile =~ s/\.y$/.l/;
	return 0 if $otherfile ne $filename && -f $otherfile;
	return 1;
}

sub is_perl_file
{
	my $filename = shift;
	# take all .pl and .pm files
	return 1 if $filename =~ /\.p[lm]$/;
	# take executable files that file(1) thinks are perl files
	return 0 unless -x $filename;
	my $file_out = `file "$filename"`;
	return $file_out =~ /:.*perl[0-9]*\b/i;
}

sub discover_files
{
	my @paths = @_;
	my @discovered;

	# Separate individual files from directories
	my @dirs;
	foreach my $path (@paths)
	{
		if (-f $path)
		{
			push(@discovered, $path);
		}
		elsif (-d $path)
		{
			push(@dirs, $path);
		}
		else
		{
			warn "Could not find $path";
		}
	}

	# Use git ls-files for directories to avoid searching build trees etc.
	if (@dirs)
	{
		# Use -z to handle files with newlines in their names, and split on \0
		# afterward.
		open(my $git_ls, '-|', 'git', 'ls-files', '-z', '--', @dirs)
		  || die "could not open git ls-files: $!";
		binmode($git_ls);
		# Slurp all output into a single string by temporarily unsetting
		# the line separator.
		my $git_output = do { local $/; <$git_ls> };
		close($git_ls);
		die "git ls-files error" if $?;
		my @git_files = split(/\0/, $git_output);
		push(@discovered, @git_files);
	}

	return @discovered;
}

sub process_file
{
	my $source_filename = shift;

	# don't try to format a file that doesn't exist
	unless (-f $source_filename)
	{
		warn "Could not find $source_filename";
		return 0;
	}

	# The more complex filtering is already done by discover_files, at this
	# point we can simply check the file extension to determine if it's a C
	# file.
	my $is_c = $source_filename =~ /\.[ch]$/;
	# All other files are Perl files
	my $is_perl = !$is_c;

	# Formatting step: pgindent or perltidy
	if ($is_c && $do_pgindent)
	{
		my $source = read_source($source_filename);
		my ($formatted, $failure) = format_c($source, $source_filename);

		if ($failure)
		{
			return 3;
		}

		if ($formatted ne $source)
		{
			if (!$diff && !$check)
			{
				write_source($formatted, $source_filename);
			}
			else
			{
				if ($diff)
				{
					my $output = diff($formatted, $source_filename);
					flock($stdout_lock_fh, LOCK_EX) or die "flock: $!";
					print $output;
					STDOUT->flush();
					flock($stdout_lock_fh, LOCK_UN) or die "flock: $!";
				}

				return 2 if $check;
			}
		}
	}
	elsif ($is_perl && $do_perltidy)
	{
		my $source = read_source($source_filename);
		my ($formatted, $failure) = format_perl($source, $source_filename);

		if ($failure)
		{
			return 3;
		}

		if ($formatted ne $source)
		{
			if (!$diff && !$check)
			{
				write_source($formatted, $source_filename);
			}
			else
			{
				if ($diff)
				{
					my $output = diff($formatted, $source_filename);
					flock($stdout_lock_fh, LOCK_EX) or die "flock: $!";
					print $output;
					STDOUT->flush();
					flock($stdout_lock_fh, LOCK_UN) or die "flock: $!";
				}

				return 2 if $check;
			}
		}
	}

	# Validation steps: perlcritic and syncheck (only for perl files)
	if ($is_perl)
	{
		if ($do_perlcritic)
		{
			my ($output, $failed) = run_perlcritic($source_filename);
			if ($failed)
			{
				flock($stdout_lock_fh, LOCK_EX) or die "flock: $!";
				print $output;
				STDOUT->flush();
				flock($stdout_lock_fh, LOCK_UN) or die "flock: $!";
				return 3;
			}
		}

		if ($do_perl_syncheck)
		{
			my ($output, $failed) = run_perl_syncheck($source_filename);
			if ($failed)
			{
				flock($stdout_lock_fh, LOCK_EX) or die "flock: $!";
				print $output;
				STDOUT->flush();
				flock($stdout_lock_fh, LOCK_UN) or die "flock: $!";
				return 3;
			}
		}
	}

	return 0;
}

sub usage
{
	my $message = shift;
	my $helptext = <<'EOF';
Usage:
pgcheck [OPTION]... [FILE|DIR]...
Options:
	--help                  show this message and quit
	--pgindent              format C code with pg_bsd_indent
	--perltidy[=PATH]       format Perl code with perltidy
	--perlcritic[=PATH]     lint Perl code with perlcritic
	--perl-syncheck         syntax-check Perl code with perl -cw
	--commit=gitref         use files modified by the named commit
	--typedefs=FILE         file containing a list of typedefs
	--list-of-typedefs=STR  string containing typedefs, space separated
	--excludes=PATH         file containing list of filename patterns to ignore
	--indent=PATH           path to pg_bsd_indent program
	--diff                  show the changes that would be made
	--check                 exit with status 2 if any changes would be made
	--jobs=N, -j N          number of parallel workers (0 = num CPUs, default 0)
When no --pgindent, --perltidy, --perlcritic, or --perl-syncheck flags are
provided, all of these tools are run.
The --excludes and --commit options can be given more than once.
EOF
	if ($help)
	{
		print $helptext;
		exit 0;
	}
	else
	{
		print STDERR "$message\n", $helptext;
		exit 1;
	}
}

# main

if ($do_pgindent)
{
	$filtered_typedefs_fh = load_typedefs();
	check_indent();
}

if ($do_perltidy)
{
	check_perltidy();
}

if ($do_perlcritic)
{
	check_perlcritic();
}

# any non-option arguments are files or directories to be processed
if (@ARGV)
{
	foreach my $f (discover_files(@ARGV))
	{
		if ($do_pgindent && is_c_file($f))
		{
			push(@files, $f);
		}
		elsif ($do_perl_any && is_perl_file($f))
		{
			push(@files, $f);
		}
	}
}

# commit file locations are relative to the source root
chdir "$sourcedir/../../.." if @commits && $sourcedir;

# process named commits by comparing each with their immediate ancestor
foreach my $commit (@commits)
{
	my $prev = "$commit~";
	my @affected = `git diff --diff-filter=ACMR --name-only $prev $commit`;
	die "git error" if $?;
	chomp(@affected);
	push(@files, grep { is_c_file($_) } @affected) if $do_pgindent;
	push(@files, grep { is_perl_file($_) } @affected) if $do_perl_any;
}

warn "No files to process" unless @files;

# remove excluded files from the file list
process_exclude();

# Used by forked children to serialize diff output to STDOUT via flock().
$stdout_lock_fh = new File::Temp(TEMPLATE => "pglockXXXXX");

# deduplicate file list
my %seen;
@files = grep { !$seen{$_}++ } @files;

my $status = 0;

if ($jobs <= 1)
{
	foreach my $source_filename (@files)
	{
		my $file_status = process_file($source_filename);
		$status = $file_status if $file_status > $status;
		last if $check && $status >= 2 && !$diff;
	}
}
else
{
	my %children;    # pid => 1

	my $file_idx = 0;
	while ($file_idx < scalar(@files) || %children)
	{
		# Fork new children up to $jobs limit
		while ($file_idx < scalar(@files) && scalar(keys %children) < $jobs)
		{
			my $source_filename = $files[ $file_idx++ ];

			my $pid = fork();
			die "fork failed: $!\n" unless defined $pid;

			if ($pid == 0)
			{
				# child
				my $child_status = process_file($source_filename);
				exit $child_status;
			}

			$children{$pid} = 1;
		}

		# Wait for at least one child to finish
		my $pid = waitpid(-1, 0);
		if ($pid > 0 && exists $children{$pid})
		{
			delete $children{$pid};
			my $child_status = $? >> 8;
			$status = $child_status if $child_status > $status;
		}
	}
}

exit $status;
