# src/test/default_collation/icu/Makefile

subdir = src/test/default_collation/icu
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

check:
	$(prove_check)

clean distclean maintainer-clean:
	rm -rf tmp_check
