# contrib/pageinspect/Makefile

MODULE_big	= pageinspect
OBJS = \
	$(WIN32RES) \
	brinfuncs.o \
	btreefuncs.o \
	fsmfuncs.o \
	ginfuncs.o \
	gistfuncs.o \
	hashfuncs.o \
	heapfuncs.o \
	rawpage.o

EXTENSION = pageinspect
DATA =  pageinspect--1.13--1.14.sql pageinspect--1.12--1.13.sql \
	pageinspect--1.11--1.12.sql pageinspect--1.10--1.11.sql \
	pageinspect--1.9--1.10.sql pageinspect--1.8--1.9.sql \
	pageinspect--1.7--1.8.sql pageinspect--1.6--1.7.sql \
	pageinspect--1.5.sql pageinspect--1.5--1.6.sql \
	pageinspect--1.4--1.5.sql pageinspect--1.3--1.4.sql \
	pageinspect--1.2--1.3.sql pageinspect--1.1--1.2.sql \
	pageinspect--1.0--1.1.sql
PGFILEDESC = "pageinspect - functions to inspect contents of database pages"

# hot_updates / hot_indexed_updates verify HOT and HOT-indexed (SIU) heap
# behaviour using pageinspect, amcheck and btree_gist together, so they live
# here (where pageinspect is built) and pull in the other two extensions.
EXTRA_INSTALL = contrib/amcheck contrib/btree_gist

# "page" is first because it creates the extension.
REGRESS = \
	page \
	brin \
	btree \
	checksum \
	gin \
	gist \
	hash \
	oldextversions \
	hot_updates \
	hot_indexed_updates

ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
subdir = contrib/pageinspect
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif
