#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for storage/direct
#
# IDENTIFICATION
#    src/backend/storage/direct/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/direct
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = directmgr.o

include $(top_srcdir)/src/backend/common.mk
