AROPT = cr

export_dynamic = -Wl,-E
ifeq ($(dir $(bindir)),$(dir $(libdir)))
rpath = -Wl,-R'$(subst $(dir $(libdir)),$$ORIGIN/../,$(rpathdir))'
ld_library_path_var =
else
rpath = -Wl,-R'$(rpathdir)'
endif

DLSUFFIX = .so

CFLAGS_SL = -fPIC -DPIC


# Rule for building a shared library from a single .o file
%.so: %.o
	$(CC) $(CFLAGS) $< $(LDFLAGS) $(LDFLAGS_SL) -shared -o $@
