#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/compression
#
# IDENTIFICATION
#    src/backend/access/compression/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/compression
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = compress_pglz.o compress_lz4.o compressamapi.o

include $(top_srcdir)/src/backend/common.mk
