CREATE OR REPLACE FUNCTION toast_acl()
RETURNS BOOLEAN AS $$
DECLARE
	I INTEGER :=0;
BEGIN
	SET LOCAL CLIENT_MIN_MESSAGES=WARNING;
	EXECUTE 'DROP TABLE IF EXISTS test2510';
	EXECUTE 'CREATE TABLE test2510 (a INT)';
	FOR I IN 1..4096 LOOP
		EXECUTE 'DROP ROLE IF EXISTS role' || I;
		EXECUTE 'CREATE ROLE role' || I;
		EXECUTE 'GRANT ALL ON test2510 TO role' || I;
	END LOOP;
	RESET CLIENT_MIN_MESSAGES;
	RETURN TRUE;
END;
$$
LANGUAGE PLPGSQL;
SELECT toast_acl();
CREATE INDEX ON test2510 USING BTREE(a);
