--
-- pg_get_table_ddl
--
-- All tests pass owner=>false so the ALTER TABLE OWNER TO line is not
-- emitted, keeping output stable across test runners (which may run under
-- different role names).
--
CREATE SCHEMA pgtbl_ddl_test;
SET search_path = pgtbl_ddl_test;

-- Basic table with PRIMARY KEY, NOT NULL, DEFAULT, COLLATE.
CREATE TABLE basic (
    id int PRIMARY KEY,
    name text NOT NULL DEFAULT 'anon' COLLATE "C"
);
SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false);

-- Identity columns (with default and custom sequence options).
CREATE TABLE id_cols (
    id_always int GENERATED ALWAYS AS IDENTITY,
    id_default int GENERATED BY DEFAULT AS IDENTITY
);
SELECT * FROM pg_get_table_ddl('id_cols'::regclass, owner => false);

CREATE TABLE id_custom (
    v int GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME id_custom_v_seq
        START WITH 100 INCREMENT BY 5
        MINVALUE 50 MAXVALUE 1000
        CACHE 10 CYCLE
    )
);
SELECT * FROM pg_get_table_ddl('id_custom'::regclass, owner => false);

-- Generated stored column.
CREATE TABLE gen_cols (
    cents int,
    dollars numeric GENERATED ALWAYS AS (cents / 100.0) STORED
);
SELECT * FROM pg_get_table_ddl('gen_cols'::regclass, owner => false);

-- Generated virtual column.
CREATE TABLE gen_virtual (
    base int,
    derived int GENERATED ALWAYS AS (base * 2) VIRTUAL
);
SELECT * FROM pg_get_table_ddl('gen_virtual'::regclass, owner => false);

-- STORAGE and COMPRESSION (only emitted when non-default for the type).
CREATE TABLE storage_cols (
    a text STORAGE EXTERNAL,
    b text STORAGE MAIN,
    c text COMPRESSION pglz
);
SELECT * FROM pg_get_table_ddl('storage_cols'::regclass, owner => false);

-- Constraints: CHECK, UNIQUE, FOREIGN KEY (DEFERRABLE).
CREATE TABLE refd (id int PRIMARY KEY);
CREATE TABLE cons (
    a int CHECK (a > 0),
    b int UNIQUE,
    c int REFERENCES refd(id) DEFERRABLE INITIALLY DEFERRED
);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false);

-- UNIQUE NULLS NOT DISTINCT (PG 15): null values are treated as equal for
-- uniqueness purposes, so the NULLS NOT DISTINCT clause must be emitted.
CREATE TABLE nulls_nd (
    a int,
    b int,
    UNIQUE NULLS NOT DISTINCT (a, b)
);
SELECT * FROM pg_get_table_ddl('nulls_nd'::regclass, owner => false);

-- INCLUDE columns on a constraint-backed UNIQUE index (PG 11): the
-- covering columns appear in an INCLUDE (...) clause on the ALTER TABLE
-- ADD CONSTRAINT statement, not in the key column list.
CREATE TABLE idx_inc (
    id   int PRIMARY KEY,
    name text,
    extra text,
    UNIQUE (name) INCLUDE (extra)
);
SELECT * FROM pg_get_table_ddl('idx_inc'::regclass, owner => false);

-- FOREIGN KEY with ON DELETE / ON UPDATE referential actions and MATCH
-- clause.  Each variant must appear verbatim in the reconstructed DDL.
CREATE TABLE fk_acts_tgt (id int PRIMARY KEY);
CREATE TABLE fk_acts (
    a int,
    b int,
    c int,
    d int,
    CONSTRAINT fk_cascade  FOREIGN KEY (a) REFERENCES fk_acts_tgt(id)
                           ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_setnull  FOREIGN KEY (b) REFERENCES fk_acts_tgt(id)
                           ON DELETE SET NULL,
    CONSTRAINT fk_setdef   FOREIGN KEY (c) REFERENCES fk_acts_tgt(id)
                           ON DELETE SET DEFAULT,
    CONSTRAINT fk_match    FOREIGN KEY (d) REFERENCES fk_acts_tgt(id)
                           MATCH FULL
);
SELECT * FROM pg_get_table_ddl('fk_acts'::regclass, owner => false);

-- NOT ENFORCED foreign key (PG 17): the constraint is recorded in the
-- catalog but not validated by the engine; NOT ENFORCED must appear in
-- the reconstructed DDL.
CREATE TABLE notenf_tgt (id int PRIMARY KEY);
CREATE TABLE notenf (
    a int,
    CONSTRAINT notenf_fk FOREIGN KEY (a) REFERENCES notenf_tgt(id)
                         NOT ENFORCED
);
SELECT * FROM pg_get_table_ddl('notenf'::regclass, owner => false);

-- Self-referencing FK: the PK must appear before the FK that references it.
-- The catalog scan returns constraints in name order; without the fix,
-- "self_ref_parent_id_fkey" sorts before "self_ref_pkey" and the FK ADD
-- CONSTRAINT fails with "there is no unique constraint matching given keys".
CREATE TABLE self_ref (
    id        int PRIMARY KEY,
    parent_id int REFERENCES self_ref(id)
);
SELECT * FROM pg_get_table_ddl('self_ref'::regclass, owner => false);

-- WITHOUT OVERLAPS on a PRIMARY KEY (PG 17): the range-type period
-- column forms a temporal primary key; WITHOUT OVERLAPS must appear
-- inside the key column list in the reconstructed ALTER TABLE.
-- Both columns use range types with native GiST support so no
-- btree_gist extension is needed.
CREATE TABLE temporal_pk (
    grp  int4range,
    during daterange,
    PRIMARY KEY (grp, during WITHOUT OVERLAPS)
);
SELECT * FROM pg_get_table_ddl('temporal_pk'::regclass, owner => false);

-- Indexes: functional and partial.  Constraint-backing indexes are
-- suppressed (they are emitted by the constraint loop).
CREATE TABLE idxd (id int PRIMARY KEY, name text);
CREATE INDEX idxd_lower ON idxd (lower(name));
CREATE INDEX idxd_partial ON idxd (id) WHERE id > 100;
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false);

-- Inheritance, including a child DEFAULT override on an inherited column.
CREATE TABLE par (a int DEFAULT 1, b text);
CREATE TABLE ch (c int) INHERITS (par);
ALTER TABLE ch ALTER COLUMN a SET DEFAULT 999;
SELECT * FROM pg_get_table_ddl('ch'::regclass, owner => false);

-- Per-column attoptions: emitted as ALTER COLUMN SET (...).
CREATE TABLE attopt (a int, b text);
ALTER TABLE attopt ALTER COLUMN a SET (n_distinct = 100);
SELECT * FROM pg_get_table_ddl('attopt'::regclass, owner => false);

-- Partitioned table parents (RANGE, HASH, and LIST).
CREATE TABLE parted_range (id int, k int) PARTITION BY RANGE (id);
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, owner => false);

CREATE TABLE parted_hash (id int) PARTITION BY HASH (id);
SELECT * FROM pg_get_table_ddl('parted_hash'::regclass, owner => false);

CREATE TABLE parted_list (id int, region text) PARTITION BY LIST (region);
SELECT * FROM pg_get_table_ddl('parted_list'::regclass, owner => false);

-- Partition children: FROM/TO, WITH (modulus, remainder), DEFAULT.
CREATE TABLE parted_range_1 PARTITION OF parted_range
    FOR VALUES FROM (0) TO (100);
ALTER TABLE parted_range_1 ALTER COLUMN k SET DEFAULT 7;
SELECT * FROM pg_get_table_ddl('parted_range_1'::regclass, owner => false);

CREATE TABLE parted_hash_0 PARTITION OF parted_hash
    FOR VALUES WITH (modulus 2, remainder 0);
SELECT * FROM pg_get_table_ddl('parted_hash_0'::regclass, owner => false);

CREATE TABLE parted_range_def PARTITION OF parted_range DEFAULT;
SELECT * FROM pg_get_table_ddl('parted_range_def'::regclass, owner => false);

-- Rules.
CREATE TABLE rt (id int);
CREATE TABLE rt_log (id int);
CREATE RULE rt_log_insert AS ON INSERT TO rt
    DO ALSO INSERT INTO rt_log VALUES (NEW.id);
SELECT * FROM pg_get_table_ddl('rt'::regclass, owner => false);

-- Extended statistics.
CREATE TABLE stx (a int, b int, c int);
CREATE STATISTICS stx_ndv (ndistinct) ON a, b FROM stx;
SELECT * FROM pg_get_table_ddl('stx'::regclass, owner => false);

-- Row-level security toggles.
CREATE TABLE rls (id int);
ALTER TABLE rls ENABLE ROW LEVEL SECURITY;
ALTER TABLE rls FORCE ROW LEVEL SECURITY;
SELECT * FROM pg_get_table_ddl('rls'::regclass, owner => false);

-- REPLICA IDENTITY: emitted only when not the default.
CREATE TABLE ri_full (a int);
ALTER TABLE ri_full REPLICA IDENTITY FULL;
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, owner => false);

CREATE TABLE ri_idx (a int NOT NULL);
CREATE UNIQUE INDEX ri_idx_a ON ri_idx (a);
ALTER TABLE ri_idx REPLICA IDENTITY USING INDEX ri_idx_a;
SELECT * FROM pg_get_table_ddl('ri_idx'::regclass, owner => false);

-- UNLOGGED + reloptions.
CREATE UNLOGGED TABLE uno (id int) WITH (fillfactor = 70);
SELECT * FROM pg_get_table_ddl('uno'::regclass, owner => false);

-- Typed table (CREATE TABLE OF type_name).  Columns inherited from the
-- type emit nothing; locally-applied DEFAULT, NOT NULL and CHECK come
-- out through a single "(col WITH OPTIONS ...)" list.
CREATE TYPE typed_t AS (a int, b text);
CREATE TABLE typed_plain OF typed_t;
SELECT * FROM pg_get_table_ddl('typed_plain'::regclass, owner => false);

CREATE TABLE typed_over OF typed_t (
    a WITH OPTIONS DEFAULT 7 NOT NULL,
    b WITH OPTIONS NOT NULL,
    CONSTRAINT b_nonempty CHECK (length(b) > 0)
);
SELECT * FROM pg_get_table_ddl('typed_over'::regclass, owner => false);

-- Temporary tables + ON COMMIT.  Temp tables must never be emitted with
-- the session-private pg_temp_NN schema prefix -- the TEMPORARY keyword
-- already places the table in pg_temp and the prefix is non-replayable.
-- ON COMMIT DROP only fires at commit, so the queries that need to see
-- the catalog entry must run in the same transaction as the CREATE.
BEGIN;
CREATE TEMP TABLE temp_default (id int);
CREATE TEMP TABLE temp_delete (id int) ON COMMIT DELETE ROWS;
CREATE TEMP TABLE temp_drop (id int) ON COMMIT DROP;

SELECT line FROM pg_get_table_ddl('temp_default'::regclass, owner => false) AS line
WHERE line LIKE 'CREATE %';

SELECT line FROM pg_get_table_ddl('temp_delete'::regclass, owner => false) AS line
WHERE line LIKE 'CREATE %';

SELECT line FROM pg_get_table_ddl('temp_drop'::regclass, owner => false) AS line
WHERE line LIKE 'CREATE %';
ROLLBACK;

-- Pretty mode.
SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, pretty => true);

-- only_kinds / except_kinds gating: each emits either only the listed kinds
-- (only_kinds) or every kind except the listed ones (except_kinds).  The two
-- are mutually exclusive.  Kind vocabulary: table, index,
-- primary_key, unique, check, foreign_key, exclusion, rule,
-- statistics, trigger, policy, rls, replica_identity, partition.
-- NOT NULL is not in the vocabulary - always emitted to prevent
-- producing schemas that silently accept NULLs the source would
-- have rejected.
--
-- except_kinds=index hides the CREATE INDEX statements.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['index']);

-- except_kinds=primary_key,unique,check,foreign_key,exclusion hides every
-- table-level constraint.  Inline CHECK in the CREATE TABLE body is
-- suppressed too.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['primary_key','unique','check','foreign_key','exclusion']);

-- except_kinds=foreign_key suppresses only FOREIGN KEY constraints;
-- PRIMARY KEY, UNIQUE, CHECK, and named NOT NULL stay.  This is the
-- first pass of the two-pass FK-clone workflow: emit tables without
-- cross-table FKs, load data, then re-run with only_kinds=foreign_key
-- to add them once all targets exist.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['foreign_key']);

-- only_kinds=foreign_key is the second pass of the two-pass FK-clone
-- workflow: emit only the ALTER TABLE ... ADD CONSTRAINT ... FOREIGN
-- KEY rows; the CREATE TABLE and every non-FK sub-object are
-- suppressed (the table already exists from the first pass).
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, only_kinds => ARRAY['foreign_key']);

-- A table with no foreign keys produces no rows under
-- only_kinds=foreign_key.
SELECT * FROM pg_get_table_ddl('refd'::regclass, owner => false, only_kinds => ARRAY['foreign_key']);

-- only_kinds=table emits only the bare CREATE TABLE (with any inline
-- column-level NOT NULL and CHECK) - no indexes, no PRIMARY KEY ALTER,
-- no other sub-objects.  Useful for capturing a table's shape without
-- pulling in everything attached to it.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['table']);

-- only_kinds=check on a non-partition table.  The constraint loop must emit
-- column-level and table-level CHECK constraints via ALTER TABLE here,
-- because the inline path in CREATE TABLE never runs (KIND_TABLE is
-- not in the filter).
CREATE TABLE chk_only (
    id  int PRIMARY KEY,
    qty int CHECK (qty > 0),
    CONSTRAINT chk_only_id_pos CHECK (id > 0)
);
SELECT * FROM pg_get_table_ddl('chk_only'::regclass, owner => false, only_kinds => ARRAY['check']);
DROP TABLE chk_only;

-- only_kinds=partition on a partitioned-table parent: each child's full DDL
-- is emitted (CREATE TABLE ... PARTITION OF ...).  The "partition"
-- keyword is a gate at the parent level; it is stripped from the
-- propagated filter so the child does not exclude its own
-- CREATE TABLE.
CREATE TABLE p_only (id int, val text) PARTITION BY RANGE (id);
CREATE TABLE p_only_a PARTITION OF p_only FOR VALUES FROM (0) TO (100);
CREATE TABLE p_only_b PARTITION OF p_only FOR VALUES FROM (100) TO (200);
SELECT * FROM pg_get_table_ddl('p_only'::regclass, owner => false, only_kinds => ARRAY['partition']);
DROP TABLE p_only;

-- only_kinds and except_kinds are mutually exclusive.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false,
                               only_kinds => ARRAY['foreign_key'],
                               except_kinds => ARRAY['foreign_key']);

-- Pub/sub schema clone: keep the table and its primary key, drop the
-- rest of the constraints so the subscriber can replicate without
-- pulling cross-table dependencies along.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['unique','check','foreign_key','exclusion']);

-- except_kinds=rule hides the CREATE RULE.
SELECT * FROM pg_get_table_ddl('rt'::regclass, owner => false, except_kinds => ARRAY['rule']);

-- except_kinds=statistics hides the CREATE STATISTICS.
SELECT * FROM pg_get_table_ddl('stx'::regclass, owner => false, except_kinds => ARRAY['statistics']);

-- except_kinds=rls hides the ENABLE/FORCE ROW LEVEL SECURITY toggles.
SELECT * FROM pg_get_table_ddl('rls'::regclass, owner => false, except_kinds => ARRAY['rls']);

-- except_kinds=replica_identity hides the REPLICA IDENTITY clause.
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, owner => false, except_kinds => ARRAY['replica_identity']);

-- Partition children are emitted by default; except_kinds=partition
-- suppresses them so only the partitioned-table parent comes out.
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, owner => false, except_kinds => ARRAY['partition']);

-- Whitespace around kind names is allowed; case is folded.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['  INDEX  ','  RULE  ']);

-- schema_qualified=false strips the schema from the target table itself
-- and from same-schema sibling references (inheritance/partition
-- parents, identity sequences in the same schema), while cross-schema
-- references are kept qualified for correctness.
--
-- Bare CREATE TABLE for an ordinary table.
SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false,
                               schema_qualified => false);

-- INHERITS parent in the same schema is emitted unqualified.
SELECT * FROM pg_get_table_ddl('ch'::regclass, owner => false,
                               schema_qualified => false);

-- Partition parent in the same schema is emitted unqualified.
SELECT * FROM pg_get_table_ddl('parted_range_1'::regclass, owner => false,
                               schema_qualified => false);

-- Cross-schema FK target keeps qualification.  The 'refd' table is in
-- pgtbl_ddl_test; place an FK target in a different schema and verify it
-- stays qualified even with schema_qualified=false.
CREATE SCHEMA pgtbl_ddl_other;
CREATE TABLE pgtbl_ddl_other.parent (id int PRIMARY KEY);
CREATE TABLE xschema_fk (
    id  int PRIMARY KEY,
    pid int REFERENCES pgtbl_ddl_other.parent
);
SELECT * FROM pg_get_table_ddl('xschema_fk'::regclass, owner => false,
                               schema_qualified => false);

-- Cross-schema FK whose target schema name ends with the base schema name
-- (e.g. "xpgtbl_ddl_test" ends with "pgtbl_ddl_test").  A post-hoc text
-- strip would mangle "xpgtbl_ddl_test.reftbl" into "xreftbl"; deciding
-- qualification at generation time avoids the problem entirely.
CREATE SCHEMA xpgtbl_ddl_test;
CREATE TABLE xpgtbl_ddl_test.reftbl (id int PRIMARY KEY);
CREATE TABLE suffix_schema_fk (
    id  int PRIMARY KEY,
    ref int REFERENCES xpgtbl_ddl_test.reftbl
);
SELECT * FROM pg_get_table_ddl('suffix_schema_fk'::regclass, owner => false,
                               schema_qualified => false);
DROP TABLE suffix_schema_fk;
DROP SCHEMA xpgtbl_ddl_test CASCADE;

-- Identity column with a custom sequence name in the same schema is
-- emitted unqualified.
SELECT * FROM pg_get_table_ddl('id_custom'::regclass, owner => false,
                               schema_qualified => false);

-- Round-trip: with schema_qualified=false, after SET search_path the
-- DDL can be replayed into a different target schema.
CREATE SCHEMA pgtbl_ddl_replay;
DO $$
DECLARE
    stmt text;
BEGIN
    SET LOCAL search_path = pgtbl_ddl_replay;
    FOR stmt IN
        SELECT line FROM pg_get_table_ddl('pgtbl_ddl_test.basic'::regclass,
                                          owner => false,
                                          schema_qualified => false) AS line
    LOOP
        EXECUTE stmt;
    END LOOP;
END $$;
SELECT relnamespace::regnamespace::text, relname
FROM pg_class WHERE oid = 'pgtbl_ddl_replay.basic'::regclass;
DROP SCHEMA pgtbl_ddl_replay CASCADE;
DROP TABLE xschema_fk;
DROP SCHEMA pgtbl_ddl_other CASCADE;

-- Cross-schema partition child with schema_qualified=false: the child must
-- carry its own schema prefix so the output is unambiguous regardless of the
-- caller's search_path.  Before the fix, the child was emitted as the bare
-- name "pt_c" (landing in whichever schema is first in search_path) while
-- the parent reference inside the CREATE TABLE came out as the fully-qualified
-- "pgtbl_ddl_part_s.pt", making the DDL inconsistent and unreplayable.
CREATE SCHEMA pgtbl_ddl_part_s;
CREATE SCHEMA pgtbl_ddl_part_other;
CREATE TABLE pgtbl_ddl_part_s.pt (id int, val int) PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_part_other.pt_c
    PARTITION OF pgtbl_ddl_part_s.pt
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_part_s.pt'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_part_s CASCADE;
DROP SCHEMA pgtbl_ddl_part_other CASCADE;

-- Locally-declared CHECK on a partition child has no inline column
-- list to live in (PARTITION OF form), so it must come out as a
-- separate ALTER TABLE ... ADD CONSTRAINT statement.
CREATE TABLE parted_chk (id int, val int) PARTITION BY RANGE (id);
CREATE TABLE parted_chk_child PARTITION OF parted_chk
    (CONSTRAINT chk_inline CHECK (val > 0))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('parted_chk_child'::regclass, owner => false);
DROP TABLE parted_chk;

-- Inheritance children of a parent with a generated column should not
-- emit an ALTER COLUMN ... SET DEFAULT for the inherited generated
-- column: the GENERATED expression carries down through inheritance,
-- and SET DEFAULT would fail at replay against a generated column.
CREATE TABLE par_gen (
    id int,
    g  int GENERATED ALWAYS AS (id * 2) STORED
);
CREATE TABLE ch_gen () INHERITS (par_gen);
SELECT * FROM pg_get_table_ddl('ch_gen'::regclass, owner => false);
DROP TABLE par_gen CASCADE;

-- A user-named NOT NULL on a local column is emitted inline as
-- "CONSTRAINT name NOT NULL" so the original name is preserved.  An
-- auto-named NOT NULL on a local column is emitted as a plain inline
-- "NOT NULL" - PG re-creates the auto-named constraint when CREATE
-- TABLE runs, so the constraint loop skips both forms to avoid the
-- redundant (and on table-rename or sequence-collision, broken)
-- ALTER TABLE ... ADD CONSTRAINT ... NOT NULL statement.
CREATE TABLE nn_named (
    a int CONSTRAINT my_nn NOT NULL,
    b int NOT NULL
);
SELECT * FROM pg_get_table_ddl('nn_named'::regclass, owner => false);
DROP TABLE nn_named;

-- Renaming the table after an IDENTITY NOT NULL column was declared
-- leaves the auto-named constraint frozen at the original name, which
-- no longer matches the post-rename "<table>_<col>_not_null" pattern.
-- The emitted DDL must still round-trip: the constraint loop must not
-- ALTER TABLE ... ADD CONSTRAINT a second NOT NULL, since CREATE TABLE
-- with the inline IDENTITY already creates an auto-NOT-NULL under the
-- new table name and PG only permits one NOT NULL per column.
CREATE TABLE nn_renamed (
    a int GENERATED ALWAYS AS IDENTITY NOT NULL
);
ALTER TABLE nn_renamed RENAME TO nn_renamed2;
SELECT * FROM pg_get_table_ddl('nn_renamed2'::regclass, owner => false);
DROP TABLE nn_renamed2;

-- Locally-declared NOT NULL on an inherited column.  The column itself
-- is omitted from the child's column list (attislocal=false), so the
-- user-named NOT NULL must come out via the post-CREATE constraint
-- loop rather than inline.
CREATE TABLE nn_par (a int);
CREATE TABLE nn_ch (b int) INHERITS (nn_par);
ALTER TABLE nn_ch ADD CONSTRAINT my_nn NOT NULL a;
SELECT * FROM pg_get_table_ddl('nn_ch'::regclass, owner => false);
DROP TABLE nn_par CASCADE;

-- schema_qualified=false must drop the schema prefix from DEFAULT
-- expressions and inline CHECK bodies that reference same-schema
-- objects (sequence via nextval, function via direct call).  This
-- relies on the deparser respecting the narrowed search_path rather
-- than on substring stripping.
CREATE SCHEMA pgtbl_ddl_xref;
CREATE SEQUENCE pgtbl_ddl_xref.myseq;
CREATE FUNCTION pgtbl_ddl_xref.f(int) RETURNS int LANGUAGE sql IMMUTABLE
    AS 'SELECT $1';
CREATE TABLE pgtbl_ddl_xref.t (
    id  int DEFAULT nextval('pgtbl_ddl_xref.myseq'),
    val int,
    CONSTRAINT chk CHECK (pgtbl_ddl_xref.f(val) > 0)
);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_xref.t'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_xref CASCADE;

-- schema_qualified=false must NOT corrupt string literals whose
-- contents happen to contain the schema name followed by a dot.  String
-- literal text is output verbatim by the deparser and is unaffected by
-- search_path narrowing.
CREATE SCHEMA pgtbl_ddl_str;
CREATE TABLE pgtbl_ddl_str.p (id int, note text) PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_str.pc PARTITION OF pgtbl_ddl_str.p
    (CONSTRAINT chk CHECK (note <> 'pgtbl_ddl_str.secret'))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_str.pc'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_str CASCADE;

-- schema_qualified=false must NOT corrupt double-quoted identifiers
-- whose contents happen to contain the schema name followed by a dot
-- (for example a column literally named "<schema>.weird" inside that
-- schema).  The mechanism is purely search_path narrowing: the deparser
-- outputs attribute names verbatim from pg_attribute, so the quoted
-- identifier content is never examined for schema prefixes.  This holds
-- even when the schema name is a single letter.
CREATE SCHEMA pgtbl_ddl_qid;
CREATE TABLE pgtbl_ddl_qid.p (id int, "pgtbl_ddl_qid.weird" int)
    PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_qid.pc PARTITION OF pgtbl_ddl_qid.p
    (CONSTRAINT chk CHECK ("pgtbl_ddl_qid.weird" > 0))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_qid.pc'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_qid CASCADE;
-- Same with a short (single-letter) schema name to confirm there is no
-- minimum-length assumption in the stripping path.
CREATE SCHEMA pgtbl_ddl_q1;
CREATE TABLE pgtbl_ddl_q1.p (id int, "pgtbl_ddl_q1.weird" int)
    PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_q1.pc PARTITION OF pgtbl_ddl_q1.p
    (CONSTRAINT chk CHECK ("pgtbl_ddl_q1.weird" > 0))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_q1.pc'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_q1 CASCADE;

-- schema_qualified=false when the base schema name itself requires
-- quoting (its prefix starts with ").  Both forms of the prefix -
-- bare-lowercase and quoted - must be stripped from outer
-- ALTER TABLE / ON / CREATE INDEX prefixes, while inner quoted
-- identifiers that happen to begin the same way must be preserved.
CREATE SCHEMA "PgTbl-Ddl-Q";
CREATE TABLE "PgTbl-Ddl-Q"."T" (id int, val int,
    CONSTRAINT chk CHECK (val > 0));
CREATE INDEX "T_val_idx" ON "PgTbl-Ddl-Q"."T" (val);
SELECT * FROM pg_get_table_ddl('"PgTbl-Ddl-Q"."T"'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA "PgTbl-Ddl-Q" CASCADE;

-- Error: not an ordinary or partitioned table.
CREATE VIEW v AS SELECT 1 AS x;
SELECT * FROM pg_get_table_ddl('v'::regclass);

CREATE SEQUENCE s;
SELECT * FROM pg_get_table_ddl('s'::regclass);

-- NULL argument returns no rows.
SELECT * FROM pg_get_table_ddl(NULL);

-- REPLICA IDENTITY USING INDEX validation: if the referenced index
-- would not be emitted (because its source kind is suppressed) but
-- replica_identity itself would be, the function raises an error so
-- the emitted DDL never dangles.  Exercise all three constraint-backed
-- forms (PK, UNIQUE, EXCLUSION) and a bare CREATE UNIQUE INDEX, in
-- both the except-list and only-list shapes.
--
-- PK-backed: except_kinds=primary_key without except_kinds=replica_identity.
CREATE TABLE ri_pk_excl (a int PRIMARY KEY);
ALTER TABLE ri_pk_excl REPLICA IDENTITY USING INDEX ri_pk_excl_pkey;
SELECT * FROM pg_get_table_ddl('ri_pk_excl'::regclass, owner => false, except_kinds => ARRAY['primary_key']);
-- Same call but also excluding replica_identity succeeds.
SELECT * FROM pg_get_table_ddl('ri_pk_excl'::regclass, owner => false, except_kinds => ARRAY['primary_key','replica_identity']);
DROP TABLE ri_pk_excl;

-- UNIQUE-constraint-backed replica identity index.
CREATE TABLE ri_uniq_excl (a int NOT NULL UNIQUE, b int);
ALTER TABLE ri_uniq_excl REPLICA IDENTITY USING INDEX ri_uniq_excl_a_key;
SELECT * FROM pg_get_table_ddl('ri_uniq_excl'::regclass, owner => false, except_kinds => ARRAY['unique']);
SELECT * FROM pg_get_table_ddl('ri_uniq_excl'::regclass, owner => false, except_kinds => ARRAY['unique','replica_identity']);
DROP TABLE ri_uniq_excl;

-- Bare CREATE UNIQUE INDEX (no backing constraint) used as REPLICA
-- IDENTITY: the index is emitted by the "index" kind, so excluding
-- "index" without also excluding "replica_identity" must error.
CREATE TABLE ri_idx_excl (a int NOT NULL, b int);
CREATE UNIQUE INDEX ri_idx_excl_a_uniq ON ri_idx_excl (a);
ALTER TABLE ri_idx_excl REPLICA IDENTITY USING INDEX ri_idx_excl_a_uniq;
SELECT * FROM pg_get_table_ddl('ri_idx_excl'::regclass, owner => false, except_kinds => ARRAY['index']);
SELECT * FROM pg_get_table_ddl('ri_idx_excl'::regclass, owner => false, except_kinds => ARRAY['index','replica_identity']);
DROP TABLE ri_idx_excl;

-- Include-side analog: only_kinds=replica_identity must include the kind
-- that emits the index, or the function errors.
CREATE TABLE ri_only (a int NOT NULL UNIQUE, b int);
ALTER TABLE ri_only REPLICA IDENTITY USING INDEX ri_only_a_key;
SELECT * FROM pg_get_table_ddl('ri_only'::regclass, owner => false, only_kinds => ARRAY['replica_identity']);
-- Including both kinds succeeds.
SELECT * FROM pg_get_table_ddl('ri_only'::regclass, owner => false, only_kinds => ARRAY['unique','replica_identity']);
DROP TABLE ri_only;

-- Per-kind only_kinds / except_kinds coverage.  For each kind in the vocabulary,
-- verify that only_kinds=K emits just that kind's output and that except_kinds=K
-- omits just that kind's output.  Kinds with no fixture above (trigger,
-- policy) are still recognized but currently emit nothing; only_kinds=K
-- returns zero rows for them.  Fixtures used:
--   idxd: PK + two secondary CREATE INDEX
--   cons: PK + UNIQUE + CHECK + FK (constraint-backed)
--   rt:   CREATE RULE
--   stx:  CREATE STATISTICS
--   rls:  ENABLE/FORCE ROW LEVEL SECURITY
--   ri_full: REPLICA IDENTITY FULL (no source-kind dependency)
CREATE TABLE excl_fix (rng int4range,
    EXCLUDE USING gist (rng WITH &&));

-- only_kinds=K: emit only kind K's statements.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['index']);
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['primary_key']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, only_kinds => ARRAY['unique']);
SELECT * FROM pg_get_table_ddl('excl_fix'::regclass, owner => false, only_kinds => ARRAY['exclusion']);
SELECT * FROM pg_get_table_ddl('rt'::regclass, owner => false, only_kinds => ARRAY['rule']);
SELECT * FROM pg_get_table_ddl('stx'::regclass, owner => false, only_kinds => ARRAY['statistics']);
SELECT * FROM pg_get_table_ddl('rls'::regclass, owner => false, only_kinds => ARRAY['rls']);
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, owner => false, only_kinds => ARRAY['replica_identity']);
-- trigger / policy are not yet implemented; uncomment when
-- pg_get_trigger_ddl / pg_get_policy_ddl helpers land.
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['trigger']);
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['policy']);

-- except_kinds=K: emit everything except kind K's statements.  PK/UNIQUE/
-- INDEX are exercised on tables without REPLICA IDENTITY USING INDEX
-- so the validation does not trip.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['primary_key']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['unique']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['check']);
SELECT * FROM pg_get_table_ddl('excl_fix'::regclass, owner => false, except_kinds => ARRAY['exclusion']);
-- trigger / policy are not yet implemented; uncomment when
-- pg_get_trigger_ddl / pg_get_policy_ddl helpers land.
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, except_kinds => ARRAY['trigger']);
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, except_kinds => ARRAY['policy']);
-- except_kinds=table suppresses the CREATE TABLE + OWNER + child-default
-- SET DEFAULT + attoptions passes, leaving only the sub-object passes.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['table']);

-- Multi-kind compositions.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['table','index']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, only_kinds => ARRAY['primary_key','foreign_key']);
-- Duplicate entries in the list are silently de-duplicated by the
-- Bitmapset.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['index','index']);

DROP TABLE excl_fix;

-- only_kinds=K on a table that does not have any K of that kind is a valid
-- filter and returns zero rows.  Tested previously with foreign_key
-- on 'refd'; here also rule, statistics, rls, replica_identity, and
-- exclusion on 'basic' (which has only PK + columns).
SELECT count(*) AS rule_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['rule']);
SELECT count(*) AS stats_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['statistics']);
SELECT count(*) AS rls_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['rls']);
SELECT count(*) AS ri_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['replica_identity']);
SELECT count(*) AS excl_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['exclusion']);

-- Input-validation edge cases for the kind array.  All
-- of these raise an error; the function never reaches relation open.
-- Empty array:
SELECT * FROM pg_get_table_ddl('basic'::regclass, only_kinds => ARRAY[]::text[]);
-- NULL element:
SELECT * FROM pg_get_table_ddl('basic'::regclass, only_kinds => ARRAY[NULL::text]);
-- Unrecognized kind:
SELECT * FROM pg_get_table_ddl('basic'::regclass, only_kinds => ARRAY['no_such_kind']);
-- Same kind specified through both parameters is still mutex-rejected.
SELECT * FROM pg_get_table_ddl('basic'::regclass,
                               only_kinds => ARRAY['index'],
                               except_kinds => ARRAY['rule']);

-- Round-trip verification.  For every test table, capture the DDL the
-- function emits, drop the schema, replay each table's DDL in
-- dependency order, and confirm that pg_get_table_ddl on the recreated
-- relation matches the original line-for-line.  The final SELECT must
-- return zero rows.
CREATE TEMP TABLE pgtbl_ddl_rt_orig (name text, ord int, line text);
INSERT INTO pgtbl_ddl_rt_orig
SELECT t.name, o.ord, o.line
FROM (VALUES
        ('basic'), ('id_cols'), ('id_custom'), ('gen_cols'), ('gen_virtual'), ('storage_cols'),
        ('refd'), ('cons'), ('nulls_nd'), ('idx_inc'),
        ('fk_acts_tgt'), ('fk_acts'), ('notenf_tgt'), ('notenf'), ('self_ref'), ('temporal_pk'),
        ('idxd'),
        ('par'), ('ch'), ('attopt'),
        ('parted_range'), ('parted_range_1'), ('parted_range_def'),
        ('parted_hash'), ('parted_hash_0'),
        ('parted_list'),
        ('rt_log'), ('rt'),
        ('stx'), ('rls'), ('ri_full'), ('ri_idx'), ('uno')
     ) AS t(name),
     LATERAL pg_get_table_ddl(('pgtbl_ddl_test.' || t.name)::regclass,
                              owner => false) WITH ORDINALITY o(line, ord);

DO $$
DECLARE
    tables CONSTANT text[] := ARRAY[
        'basic', 'id_cols', 'id_custom', 'gen_cols', 'gen_virtual', 'storage_cols',
        'refd', 'cons', 'nulls_nd', 'idx_inc',
        'fk_acts_tgt', 'fk_acts', 'notenf_tgt', 'notenf', 'self_ref', 'temporal_pk',
        'idxd',
        'par', 'ch', 'attopt',
        'parted_range', 'parted_range_1', 'parted_range_def',
        'parted_hash', 'parted_hash_0',
        'parted_list',
        'rt_log', 'rt',
        'stx', 'rls', 'ri_full', 'ri_idx', 'uno'
    ];
    t text;
    stmt text;
BEGIN
    DROP SCHEMA pgtbl_ddl_test CASCADE;
    CREATE SCHEMA pgtbl_ddl_test;
    FOREACH t IN ARRAY tables LOOP
        FOR stmt IN
            SELECT line FROM pgtbl_ddl_rt_orig WHERE name = t ORDER BY ord
        LOOP
            BEGIN
                EXECUTE stmt;
            EXCEPTION WHEN duplicate_table THEN
                NULL;  -- partition child already created by its parent's DDL
            END;
        END LOOP;
    END LOOP;
END $$;

WITH after_ddl AS (
    SELECT t.name, o.ord, o.line
    FROM (SELECT DISTINCT name FROM pgtbl_ddl_rt_orig) AS t,
         LATERAL pg_get_table_ddl(('pgtbl_ddl_test.' || t.name)::regclass,
                                  owner => false) WITH ORDINALITY o(line, ord)
)
(SELECT 'missing-in-copy' AS kind, name, ord, line FROM pgtbl_ddl_rt_orig
 EXCEPT
 SELECT 'missing-in-copy', name, ord, line FROM after_ddl)
UNION ALL
(SELECT 'extra-in-copy' AS kind, name, ord, line FROM after_ddl
 EXCEPT
 SELECT 'extra-in-copy', name, ord, line FROM pgtbl_ddl_rt_orig)
ORDER BY kind, name, ord;

-- Cleanup.
DROP SCHEMA pgtbl_ddl_test CASCADE;
