--
-- pg_get_table_ddl
--
-- All tests pass owner=>false so the ALTER TABLE OWNER TO line is not
-- emitted, keeping output stable across test runners (which may run under
-- different role names).
--
CREATE SCHEMA pgtbl_ddl_test;
SET search_path = pgtbl_ddl_test;

-- Basic table with PRIMARY KEY, NOT NULL, DEFAULT, COLLATE.
CREATE TABLE basic (
    id int PRIMARY KEY,
    name text NOT NULL DEFAULT 'anon' COLLATE "C"
);
SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false);

-- Identity columns (with default and custom sequence options).
CREATE TABLE id_cols (
    id_always int GENERATED ALWAYS AS IDENTITY,
    id_default int GENERATED BY DEFAULT AS IDENTITY
);
SELECT * FROM pg_get_table_ddl('id_cols'::regclass, owner => false);

CREATE TABLE id_custom (
    v int GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME id_custom_v_seq
        START WITH 100 INCREMENT BY 5
        MINVALUE 50 MAXVALUE 1000
        CACHE 10 CYCLE
    )
);
SELECT * FROM pg_get_table_ddl('id_custom'::regclass, owner => false);

-- Generated stored column.
CREATE TABLE gen_cols (
    cents int,
    dollars numeric GENERATED ALWAYS AS (cents / 100.0) STORED
);
SELECT * FROM pg_get_table_ddl('gen_cols'::regclass, owner => false);

-- Generated virtual column.
CREATE TABLE gen_virtual (
    base int,
    derived int GENERATED ALWAYS AS (base * 2) VIRTUAL
);
SELECT * FROM pg_get_table_ddl('gen_virtual'::regclass, owner => false);

-- STORAGE and COMPRESSION (only emitted when non-default for the type).
CREATE TABLE storage_cols (
    a text STORAGE EXTERNAL,
    b text STORAGE MAIN,
    c text COMPRESSION pglz
);
SELECT * FROM pg_get_table_ddl('storage_cols'::regclass, owner => false);

-- STORAGE PLAIN: text defaults to EXTENDED; PLAIN must be emitted when set
-- explicitly because it changes toast behaviour (forces inline storage).
CREATE TABLE storage_plain (a text STORAGE PLAIN, b bytea STORAGE PLAIN);
SELECT * FROM pg_get_table_ddl('storage_plain'::regclass, owner => false);

-- Constraints: CHECK, UNIQUE, FOREIGN KEY (DEFERRABLE).
CREATE TABLE refd (id int PRIMARY KEY);
CREATE TABLE cons (
    a int CHECK (a > 0),
    b int UNIQUE,
    c int REFERENCES refd(id) DEFERRABLE INITIALLY DEFERRED
);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false);

-- UNIQUE NULLS NOT DISTINCT (PG 15): null values are treated as equal for
-- uniqueness purposes, so the NULLS NOT DISTINCT clause must be emitted.
CREATE TABLE nulls_nd (
    a int,
    b int,
    UNIQUE NULLS NOT DISTINCT (a, b)
);
SELECT * FROM pg_get_table_ddl('nulls_nd'::regclass, owner => false);

-- INCLUDE columns on a constraint-backed UNIQUE index (PG 11): the
-- covering columns appear in an INCLUDE (...) clause on the ALTER TABLE
-- ADD CONSTRAINT statement, not in the key column list.
CREATE TABLE idx_inc (
    id   int PRIMARY KEY,
    name text,
    extra text,
    UNIQUE (name) INCLUDE (extra)
);
SELECT * FROM pg_get_table_ddl('idx_inc'::regclass, owner => false);

-- FOREIGN KEY with ON DELETE / ON UPDATE referential actions and MATCH
-- clause.  Each variant must appear verbatim in the reconstructed DDL.
CREATE TABLE fk_acts_tgt (id int PRIMARY KEY);
CREATE TABLE fk_acts (
    a int,
    b int,
    c int,
    d int,
    CONSTRAINT fk_cascade  FOREIGN KEY (a) REFERENCES fk_acts_tgt(id)
                           ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_setnull  FOREIGN KEY (b) REFERENCES fk_acts_tgt(id)
                           ON DELETE SET NULL,
    CONSTRAINT fk_setdef   FOREIGN KEY (c) REFERENCES fk_acts_tgt(id)
                           ON DELETE SET DEFAULT,
    CONSTRAINT fk_match    FOREIGN KEY (d) REFERENCES fk_acts_tgt(id)
                           MATCH FULL
);
SELECT * FROM pg_get_table_ddl('fk_acts'::regclass, owner => false);

-- ON DELETE RESTRICT and ON UPDATE CASCADE / SET NULL / SET DEFAULT: the
-- remaining referential-action combinations not covered by fk_acts above.
CREATE TABLE fk_upd_tgt (id int PRIMARY KEY);
CREATE TABLE fk_upd_acts (
    a int CONSTRAINT fk_delete_restrict   REFERENCES fk_upd_tgt(id)
                          ON DELETE RESTRICT,
    b int CONSTRAINT fk_update_cascade    REFERENCES fk_upd_tgt(id)
                          ON UPDATE CASCADE,
    c int CONSTRAINT fk_update_setdefault REFERENCES fk_upd_tgt(id)
                          ON UPDATE SET DEFAULT,
    d int CONSTRAINT fk_update_setnull    REFERENCES fk_upd_tgt(id)
                          ON UPDATE SET NULL
);
SELECT * FROM pg_get_table_ddl('fk_upd_acts'::regclass, owner => false);

-- DEFERRABLE INITIALLY IMMEDIATE: the deferrable-but-not-deferred variant.
-- INITIALLY IMMEDIATE is the default for DEFERRABLE constraints, so the
-- deparser omits it; only DEFERRABLE itself must appear in the output.
CREATE TABLE fk_def_imm_tgt (id int PRIMARY KEY);
CREATE TABLE fk_def_imm (
    a int REFERENCES fk_def_imm_tgt(id) DEFERRABLE INITIALLY IMMEDIATE
);
SELECT * FROM pg_get_table_ddl('fk_def_imm'::regclass, owner => false);

-- NOT ENFORCED foreign key (PG 17): the constraint is recorded in the
-- catalog but not validated by the engine; NOT ENFORCED must appear in
-- the reconstructed DDL.
CREATE TABLE notenf_tgt (id int PRIMARY KEY);
CREATE TABLE notenf (
    a int,
    CONSTRAINT notenf_fk FOREIGN KEY (a) REFERENCES notenf_tgt(id)
                         NOT ENFORCED
);
SELECT * FROM pg_get_table_ddl('notenf'::regclass, owner => false);

-- Self-referencing FK: the PK must appear before the FK that references it.
-- The catalog scan returns constraints in name order; without the fix,
-- "self_ref_parent_id_fkey" sorts before "self_ref_pkey" and the FK ADD
-- CONSTRAINT fails with "there is no unique constraint matching given keys".
CREATE TABLE self_ref (
    id        int PRIMARY KEY,
    parent_id int REFERENCES self_ref(id)
);
SELECT * FROM pg_get_table_ddl('self_ref'::regclass, owner => false);

-- WITHOUT OVERLAPS on a PRIMARY KEY (PG 17): the range-type period
-- column forms a temporal primary key; WITHOUT OVERLAPS must appear
-- inside the key column list in the reconstructed ALTER TABLE.
-- Both columns use range types with native GiST support so no
-- btree_gist extension is needed.
CREATE TABLE temporal_pk (
    grp  int4range,
    during daterange,
    PRIMARY KEY (grp, during WITHOUT OVERLAPS)
);
SELECT * FROM pg_get_table_ddl('temporal_pk'::regclass, owner => false);

-- Indexes: functional and partial.  Constraint-backing indexes are
-- suppressed (they are emitted by the constraint loop).
CREATE TABLE idxd (id int PRIMARY KEY, name text);
CREATE INDEX idxd_lower ON idxd (lower(name));
CREATE INDEX idxd_partial ON idxd (id) WHERE id > 100;
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false);

-- Inheritance, including a child DEFAULT override on an inherited column.
CREATE TABLE par (a int DEFAULT 1, b text);
CREATE TABLE ch (c int) INHERITS (par);
ALTER TABLE ch ALTER COLUMN a SET DEFAULT 999;
SELECT * FROM pg_get_table_ddl('ch'::regclass, owner => false);

-- Per-column attoptions: emitted as ALTER COLUMN SET (...).
CREATE TABLE attopt (a int, b text);
ALTER TABLE attopt ALTER COLUMN a SET (n_distinct = 100);
SELECT * FROM pg_get_table_ddl('attopt'::regclass, owner => false);

-- Partitioned table parents (RANGE, HASH, and LIST).
CREATE TABLE parted_range (id int, k int) PARTITION BY RANGE (id);
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, owner => false);

CREATE TABLE parted_hash (id int) PARTITION BY HASH (id);
SELECT * FROM pg_get_table_ddl('parted_hash'::regclass, owner => false);

CREATE TABLE parted_list (id int, region text) PARTITION BY LIST (region);
SELECT * FROM pg_get_table_ddl('parted_list'::regclass, owner => false);

-- Partition children: FROM/TO, WITH (modulus, remainder), DEFAULT.
CREATE TABLE parted_range_1 PARTITION OF parted_range
    FOR VALUES FROM (0) TO (100);
ALTER TABLE parted_range_1 ALTER COLUMN k SET DEFAULT 7;
SELECT * FROM pg_get_table_ddl('parted_range_1'::regclass, owner => false);

CREATE TABLE parted_hash_0 PARTITION OF parted_hash
    FOR VALUES WITH (modulus 2, remainder 0);
SELECT * FROM pg_get_table_ddl('parted_hash_0'::regclass, owner => false);

CREATE TABLE parted_range_def PARTITION OF parted_range DEFAULT;
SELECT * FROM pg_get_table_ddl('parted_range_def'::regclass, owner => false);

-- Non-constraint-backed index on a partitioned table: partition children are
-- emitted before the parent's indexes so PARTITION OF runs without any parent
-- index present (preventing auto-creation of child indexes).  Each child index
-- is emitted explicitly; the parent index follows with ON ONLY and then
-- ALTER INDEX ... ATTACH PARTITION for each child.
CREATE TABLE parted_idx (id int, region text) PARTITION BY LIST (region);
CREATE TABLE parted_idx_a PARTITION OF parted_idx FOR VALUES IN ('a');
CREATE UNIQUE INDEX parted_idx_uidx ON parted_idx (id, region);
SELECT * FROM pg_get_table_ddl('parted_idx'::regclass, owner => false);

-- Plain (non-unique) CREATE INDEX on partitioned table: same pattern.
CREATE TABLE parted_plain (id int, val text) PARTITION BY RANGE (id);
CREATE TABLE parted_plain_a PARTITION OF parted_plain FOR VALUES FROM (0) TO (100);
CREATE INDEX parted_plain_id_idx ON parted_plain (id);
SELECT * FROM pg_get_table_ddl('parted_plain'::regclass, owner => false);

-- Constraint-backed PRIMARY KEY on partitioned table: the child's inherited
-- constraint (conislocal=false) and its backing index are both suppressed.
CREATE TABLE parted_pk (id int, region text) PARTITION BY LIST (region);
CREATE TABLE parted_pk_a PARTITION OF parted_pk FOR VALUES IN ('a');
ALTER TABLE parted_pk ADD PRIMARY KEY (id, region);
SELECT * FROM pg_get_table_ddl('parted_pk'::regclass, owner => false);

-- Multi-level (sub-partitioned) table with a CREATE INDEX on the root.
-- All partition tables are emitted depth-first before any indexes; then each
-- level emits CREATE INDEX ON ONLY followed by ATTACH PARTITION for its children.
CREATE TABLE parted_sub (id int, region text) PARTITION BY LIST (region);
CREATE TABLE parted_sub_a PARTITION OF parted_sub
    FOR VALUES IN ('a') PARTITION BY RANGE (id);
CREATE TABLE parted_sub_a1 PARTITION OF parted_sub_a FOR VALUES FROM (0) TO (100);
CREATE INDEX parted_sub_id_idx ON parted_sub (id);
SELECT * FROM pg_get_table_ddl('parted_sub'::regclass, owner => false);

-- Partition child with its own locally-defined index (relispartition=false):
-- this is NOT inherited from any parent partitioned index and must be emitted.
CREATE TABLE parted_child_idx (id int, region text) PARTITION BY LIST (region);
CREATE TABLE parted_child_idx_a PARTITION OF parted_child_idx FOR VALUES IN ('a');
CREATE INDEX parted_child_idx_a_id ON parted_child_idx_a (id);
SELECT * FROM pg_get_table_ddl('parted_child_idx'::regclass, owner => false);

-- Mix: parent has a CREATE INDEX (emitted ON ONLY, child gets ATTACH) AND the
-- child also has its own local index (relispartition=false, emitted separately).
CREATE TABLE parted_mixed (id int, region text) PARTITION BY LIST (region);
CREATE TABLE parted_mixed_a PARTITION OF parted_mixed FOR VALUES IN ('a');
CREATE INDEX parted_mixed_id ON parted_mixed (id);
CREATE INDEX parted_mixed_a_region ON parted_mixed_a (region);
SELECT * FROM pg_get_table_ddl('parted_mixed'::regclass, owner => false);

-- FK on a partitioned table: declared on the parent; partition children inherit
-- the constraint with conislocal=false and must not re-emit it.
CREATE TABLE parted_fk_tgt (id int PRIMARY KEY);
CREATE TABLE parted_fk (id int, tgt_id int REFERENCES parted_fk_tgt(id))
    PARTITION BY RANGE (id);
CREATE TABLE parted_fk_a PARTITION OF parted_fk FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('parted_fk'::regclass, owner => false);

-- Statistics declared explicitly on a partition child (not auto-propagated):
-- the child's statistics object appears inside the child's DDL block.
CREATE TABLE parted_stx (id int, region text, val float) PARTITION BY LIST (region);
CREATE TABLE parted_stx_a PARTITION OF parted_stx FOR VALUES IN ('a');
CREATE STATISTICS parted_stx_stat (ndistinct) ON id, region FROM parted_stx;
CREATE STATISTICS parted_stx_a_stat (ndistinct) ON id, val FROM parted_stx_a;
SELECT * FROM pg_get_table_ddl('parted_stx'::regclass, owner => false);
DROP TABLE parted_stx;

-- NO INHERIT CHECK constraint: the NO INHERIT flag must appear verbatim in the
-- inline constraint definition inside the CREATE TABLE body.
CREATE TABLE noinhchk (id int, val int,
    CONSTRAINT val_pos CHECK (val > 0) NO INHERIT);
SELECT * FROM pg_get_table_ddl('noinhchk'::regclass, owner => false);
DROP TABLE noinhchk;

-- Multiple inheritance parents: the INHERITS clause must list both parents in
-- declaration order; only the locally-defined column appears in the column list.
CREATE TABLE mi_p1 (a int DEFAULT 1);
CREATE TABLE mi_p2 (b text DEFAULT 'x');
CREATE TABLE mi_child (c float) INHERITS (mi_p1, mi_p2);
SELECT * FROM pg_get_table_ddl('mi_child'::regclass, owner => false);
DROP TABLE mi_p1, mi_p2 CASCADE;

-- Rules.
CREATE TABLE rt (id int);
CREATE TABLE rt_log (id int);
CREATE RULE rt_log_insert AS ON INSERT TO rt
    DO ALSO INSERT INTO rt_log VALUES (NEW.id);
SELECT * FROM pg_get_table_ddl('rt'::regclass, owner => false);

-- Extended statistics.
CREATE TABLE stx (a int, b int, c int);
CREATE STATISTICS stx_ndv (ndistinct) ON a, b FROM stx;
SELECT * FROM pg_get_table_ddl('stx'::regclass, owner => false);

-- Row-level security toggles.
CREATE TABLE rls (id int);
ALTER TABLE rls ENABLE ROW LEVEL SECURITY;
ALTER TABLE rls FORCE ROW LEVEL SECURITY;
SELECT * FROM pg_get_table_ddl('rls'::regclass, owner => false);

-- RLS with policies: a WARNING must be raised because pg_get_table_ddl cannot
-- yet emit CREATE POLICY statements.  Replaying without the warning would
-- produce a table with RLS enabled but no policies, silently denying all rows.
CREATE TABLE rls_pol (id int);
ALTER TABLE rls_pol ENABLE ROW LEVEL SECURITY;
CREATE POLICY rls_pol_p ON rls_pol USING (id > 0);
SELECT * FROM pg_get_table_ddl('rls_pol'::regclass, owner => false);
DROP TABLE rls_pol;

-- REPLICA IDENTITY: emitted only when not the default.
CREATE TABLE ri_full (a int);
ALTER TABLE ri_full REPLICA IDENTITY FULL;
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, owner => false);

CREATE TABLE ri_idx (a int NOT NULL);
CREATE UNIQUE INDEX ri_idx_a ON ri_idx (a);
ALTER TABLE ri_idx REPLICA IDENTITY USING INDEX ri_idx_a;
SELECT * FROM pg_get_table_ddl('ri_idx'::regclass, owner => false);

-- UNLOGGED + reloptions.
CREATE UNLOGGED TABLE uno (id int) WITH (fillfactor = 70);
SELECT * FROM pg_get_table_ddl('uno'::regclass, owner => false);

-- Typed table (CREATE TABLE OF type_name).  Columns inherited from the
-- type emit nothing; locally-applied DEFAULT, NOT NULL and CHECK come
-- out through a single "(col WITH OPTIONS ...)" list.
CREATE TYPE typed_t AS (a int, b text);
CREATE TABLE typed_plain OF typed_t;
SELECT * FROM pg_get_table_ddl('typed_plain'::regclass, owner => false);

CREATE TABLE typed_over OF typed_t (
    a WITH OPTIONS DEFAULT 7 NOT NULL,
    b WITH OPTIONS NOT NULL,
    CONSTRAINT b_nonempty CHECK (length(b) > 0)
);
SELECT * FROM pg_get_table_ddl('typed_over'::regclass, owner => false);

-- Temporary tables + ON COMMIT.  Temp tables must never be emitted with
-- the session-private pg_temp_NN schema prefix -- the TEMPORARY keyword
-- already places the table in pg_temp and the prefix is non-replayable.
-- ON COMMIT DROP only fires at commit, so the queries that need to see
-- the catalog entry must run in the same transaction as the CREATE.
BEGIN;
CREATE TEMP TABLE temp_default (id int);
CREATE TEMP TABLE temp_delete (id int) ON COMMIT DELETE ROWS;
CREATE TEMP TABLE temp_drop (id int) ON COMMIT DROP;

SELECT line FROM pg_get_table_ddl('temp_default'::regclass, owner => false) AS line
WHERE line LIKE 'CREATE %';

SELECT line FROM pg_get_table_ddl('temp_delete'::regclass, owner => false) AS line
WHERE line LIKE 'CREATE %';

SELECT line FROM pg_get_table_ddl('temp_drop'::regclass, owner => false) AS line
WHERE line LIKE 'CREATE %';
ROLLBACK;

-- Pretty mode.
SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, pretty => true);

-- owner => true (the default) emits ALTER TABLE ... OWNER TO.  Verify the
-- line is present without depending on the role name used by the test runner.
SELECT count(*) AS owner_lines
FROM pg_get_table_ddl('basic'::regclass, owner => true)
WHERE pg_get_table_ddl LIKE 'ALTER TABLE % OWNER TO %';

-- only_kinds / except_kinds gating: each emits either only the listed kinds
-- (only_kinds) or every kind except the listed ones (except_kinds).  The two
-- are mutually exclusive.  Kind vocabulary: table, index,
-- primary_key, unique, check, foreign_key, exclusion, rule,
-- statistics, trigger, policy, rls, replica_identity, partition.
-- NOT NULL is not in the vocabulary - always emitted to prevent
-- producing schemas that silently accept NULLs the source would
-- have rejected.
--
-- except_kinds=index hides the CREATE INDEX statements.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['index']);

-- except_kinds=primary_key,unique,check,foreign_key,exclusion hides every
-- table-level constraint.  Inline CHECK in the CREATE TABLE body is
-- suppressed too.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['primary_key','unique','check','foreign_key','exclusion']);

-- except_kinds=foreign_key suppresses only FOREIGN KEY constraints;
-- PRIMARY KEY, UNIQUE, CHECK, and named NOT NULL stay.  This is the
-- first pass of the two-pass FK-clone workflow: emit tables without
-- cross-table FKs, load data, then re-run with only_kinds=foreign_key
-- to add them once all targets exist.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['foreign_key']);

-- only_kinds=foreign_key is the second pass of the two-pass FK-clone
-- workflow: emit only the ALTER TABLE ... ADD CONSTRAINT ... FOREIGN
-- KEY rows; the CREATE TABLE and every non-FK sub-object are
-- suppressed (the table already exists from the first pass).
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, only_kinds => ARRAY['foreign_key']);

-- A table with no foreign keys produces no rows under
-- only_kinds=foreign_key.
SELECT * FROM pg_get_table_ddl('refd'::regclass, owner => false, only_kinds => ARRAY['foreign_key']);

-- only_kinds=table emits only the bare CREATE TABLE (with any inline
-- column-level NOT NULL and CHECK) - no indexes, no PRIMARY KEY ALTER,
-- no other sub-objects.  Useful for capturing a table's shape without
-- pulling in everything attached to it.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['table']);

-- only_kinds=check on a non-partition table.  The constraint loop must emit
-- column-level and table-level CHECK constraints via ALTER TABLE here,
-- because the inline path in CREATE TABLE never runs (KIND_TABLE is
-- not in the filter).
CREATE TABLE chk_only (
    id  int PRIMARY KEY,
    qty int CHECK (qty > 0),
    CONSTRAINT chk_only_id_pos CHECK (id > 0)
);
SELECT * FROM pg_get_table_ddl('chk_only'::regclass, owner => false, only_kinds => ARRAY['check']);
DROP TABLE chk_only;

-- only_kinds=partition on a partitioned-table parent: each child's full DDL
-- is emitted (CREATE TABLE ... PARTITION OF ...).  The "partition"
-- keyword is a gate at the parent level; it is stripped from the
-- propagated filter so the child does not exclude its own
-- CREATE TABLE.
CREATE TABLE p_only (id int, val text) PARTITION BY RANGE (id);
CREATE TABLE p_only_a PARTITION OF p_only FOR VALUES FROM (0) TO (100);
CREATE TABLE p_only_b PARTITION OF p_only FOR VALUES FROM (100) TO (200);
SELECT * FROM pg_get_table_ddl('p_only'::regclass, owner => false, only_kinds => ARRAY['partition']);
DROP TABLE p_only;

-- only_kinds and except_kinds are mutually exclusive.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false,
                               only_kinds => ARRAY['foreign_key'],
                               except_kinds => ARRAY['foreign_key']);

-- Pub/sub schema clone: keep the table and its primary key, drop the
-- rest of the constraints so the subscriber can replicate without
-- pulling cross-table dependencies along.
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['unique','check','foreign_key','exclusion']);

-- except_kinds=rule hides the CREATE RULE.
SELECT * FROM pg_get_table_ddl('rt'::regclass, owner => false, except_kinds => ARRAY['rule']);

-- except_kinds=statistics hides the CREATE STATISTICS.
SELECT * FROM pg_get_table_ddl('stx'::regclass, owner => false, except_kinds => ARRAY['statistics']);

-- except_kinds=rls hides the ENABLE/FORCE ROW LEVEL SECURITY toggles.
SELECT * FROM pg_get_table_ddl('rls'::regclass, owner => false, except_kinds => ARRAY['rls']);

-- except_kinds=replica_identity hides the REPLICA IDENTITY clause.
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, owner => false, except_kinds => ARRAY['replica_identity']);

-- Partition children are emitted by default; except_kinds=partition
-- suppresses them so only the partitioned-table parent comes out.
SELECT * FROM pg_get_table_ddl('parted_range'::regclass, owner => false, except_kinds => ARRAY['partition']);

-- Whitespace around kind names is allowed; case is folded.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['  INDEX  ','  RULE  ']);

-- schema_qualified=false strips the schema from the target table itself
-- and from same-schema sibling references (inheritance/partition
-- parents, identity sequences in the same schema), while cross-schema
-- references are kept qualified for correctness.
--
-- Bare CREATE TABLE for an ordinary table.
SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false,
                               schema_qualified => false);

-- INHERITS parent in the same schema is emitted unqualified.
SELECT * FROM pg_get_table_ddl('ch'::regclass, owner => false,
                               schema_qualified => false);

-- Partition parent in the same schema is emitted unqualified.
SELECT * FROM pg_get_table_ddl('parted_range_1'::regclass, owner => false,
                               schema_qualified => false);

-- Cross-schema FK target keeps qualification.  The 'refd' table is in
-- pgtbl_ddl_test; place an FK target in a different schema and verify it
-- stays qualified even with schema_qualified=false.
CREATE SCHEMA pgtbl_ddl_other;
CREATE TABLE pgtbl_ddl_other.parent (id int PRIMARY KEY);
CREATE TABLE xschema_fk (
    id  int PRIMARY KEY,
    pid int REFERENCES pgtbl_ddl_other.parent
);
SELECT * FROM pg_get_table_ddl('xschema_fk'::regclass, owner => false,
                               schema_qualified => false);

-- Cross-schema FK whose target schema name ends with the base schema name
-- (e.g. "xpgtbl_ddl_test" ends with "pgtbl_ddl_test").  A post-hoc text
-- strip would mangle "xpgtbl_ddl_test.reftbl" into "xreftbl"; deciding
-- qualification at generation time avoids the problem entirely.
CREATE SCHEMA xpgtbl_ddl_test;
CREATE TABLE xpgtbl_ddl_test.reftbl (id int PRIMARY KEY);
CREATE TABLE suffix_schema_fk (
    id  int PRIMARY KEY,
    ref int REFERENCES xpgtbl_ddl_test.reftbl
);
SELECT * FROM pg_get_table_ddl('suffix_schema_fk'::regclass, owner => false,
                               schema_qualified => false);
DROP TABLE suffix_schema_fk;
DROP SCHEMA xpgtbl_ddl_test CASCADE;

-- Identity column with a custom sequence name in the same schema is
-- emitted unqualified.
SELECT * FROM pg_get_table_ddl('id_custom'::regclass, owner => false,
                               schema_qualified => false);

-- Round-trip: with schema_qualified=false, after SET search_path the
-- DDL can be replayed into a different target schema.
CREATE SCHEMA pgtbl_ddl_replay;
DO $$
DECLARE
    stmt text;
BEGIN
    SET LOCAL search_path = pgtbl_ddl_replay;
    FOR stmt IN
        SELECT line FROM pg_get_table_ddl('pgtbl_ddl_test.basic'::regclass,
                                          owner => false,
                                          schema_qualified => false) AS line
    LOOP
        EXECUTE stmt;
    END LOOP;
END $$;
SELECT relnamespace::regnamespace::text, relname
FROM pg_class WHERE oid = 'pgtbl_ddl_replay.basic'::regclass;
DROP SCHEMA pgtbl_ddl_replay CASCADE;
DROP TABLE xschema_fk;
DROP SCHEMA pgtbl_ddl_other CASCADE;

-- Cross-schema partition child with schema_qualified=false: the child must
-- carry its own schema prefix so the output is unambiguous regardless of the
-- caller's search_path.  Before the fix, the child was emitted as the bare
-- name "pt_c" (landing in whichever schema is first in search_path) while
-- the parent reference inside the CREATE TABLE came out as the fully-qualified
-- "pgtbl_ddl_part_s.pt", making the DDL inconsistent and unreplayable.
CREATE SCHEMA pgtbl_ddl_part_s;
CREATE SCHEMA pgtbl_ddl_part_other;
CREATE TABLE pgtbl_ddl_part_s.pt (id int, val int) PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_part_other.pt_c
    PARTITION OF pgtbl_ddl_part_s.pt
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_part_s.pt'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_part_s CASCADE;
DROP SCHEMA pgtbl_ddl_part_other CASCADE;

-- Locally-declared CHECK on a partition child has no inline column
-- list to live in (PARTITION OF form), so it must come out as a
-- separate ALTER TABLE ... ADD CONSTRAINT statement.
CREATE TABLE parted_chk (id int, val int) PARTITION BY RANGE (id);
CREATE TABLE parted_chk_child PARTITION OF parted_chk
    (CONSTRAINT chk_inline CHECK (val > 0))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('parted_chk_child'::regclass, owner => false);
DROP TABLE parted_chk;

-- Inheritance children of a parent with a generated column should not
-- emit an ALTER COLUMN ... SET DEFAULT for the inherited generated
-- column: the GENERATED expression carries down through inheritance,
-- and SET DEFAULT would fail at replay against a generated column.
CREATE TABLE par_gen (
    id int,
    g  int GENERATED ALWAYS AS (id * 2) STORED
);
CREATE TABLE ch_gen () INHERITS (par_gen);
SELECT * FROM pg_get_table_ddl('ch_gen'::regclass, owner => false);
DROP TABLE par_gen CASCADE;

-- A user-named NOT NULL on a local column is emitted inline as
-- "CONSTRAINT name NOT NULL" so the original name is preserved.  An
-- auto-named NOT NULL on a local column is emitted as a plain inline
-- "NOT NULL" - PG re-creates the auto-named constraint when CREATE
-- TABLE runs, so the constraint loop skips both forms to avoid the
-- redundant (and on table-rename or sequence-collision, broken)
-- ALTER TABLE ... ADD CONSTRAINT ... NOT NULL statement.
CREATE TABLE nn_named (
    a int CONSTRAINT my_nn NOT NULL,
    b int NOT NULL
);
SELECT * FROM pg_get_table_ddl('nn_named'::regclass, owner => false);
DROP TABLE nn_named;

-- Renaming the table after an IDENTITY NOT NULL column was declared
-- leaves the auto-named constraint frozen at the original name, which
-- no longer matches the post-rename "<table>_<col>_not_null" pattern.
-- The emitted DDL must still round-trip: the constraint loop must not
-- ALTER TABLE ... ADD CONSTRAINT a second NOT NULL, since CREATE TABLE
-- with the inline IDENTITY already creates an auto-NOT-NULL under the
-- new table name and PG only permits one NOT NULL per column.
CREATE TABLE nn_renamed (
    a int GENERATED ALWAYS AS IDENTITY NOT NULL
);
ALTER TABLE nn_renamed RENAME TO nn_renamed2;
SELECT * FROM pg_get_table_ddl('nn_renamed2'::regclass, owner => false);
DROP TABLE nn_renamed2;

-- Locally-declared NOT NULL on an inherited column.  The column itself
-- is omitted from the child's own column list (attislocal=false), so the
-- user-named NOT NULL is emitted as a table-level CONSTRAINT clause in
-- the CREATE TABLE body.  This preserves the name and prevents a collision
-- when the parent later propagates its own NOT NULL to the child.
CREATE TABLE nn_par (a int);
CREATE TABLE nn_ch (b int) INHERITS (nn_par);
ALTER TABLE nn_ch ADD CONSTRAINT my_nn NOT NULL a;
SELECT * FROM pg_get_table_ddl('nn_ch'::regclass, owner => false);
DROP TABLE nn_par CASCADE;

-- Partition child where the parent's default was explicitly dropped.
-- After PARTITION OF the parent default is re-applied; DROP DEFAULT
-- must be emitted to restore the dropped state.
CREATE TABLE drop_def_par (a int DEFAULT 99) PARTITION BY LIST (a);
CREATE TABLE drop_def_child PARTITION OF drop_def_par FOR VALUES IN (1);
ALTER TABLE ONLY drop_def_child ALTER COLUMN a DROP DEFAULT;
SELECT * FROM pg_get_table_ddl('drop_def_child'::regclass, owner => false);
DROP TABLE drop_def_par;

-- Named NOT NULL on a partition child that was attached from a pre-existing
-- table.  The name must be preserved via the PARTITION OF column spec list
-- so the child keeps its local name rather than inheriting the parent's
-- auto-generated name.
CREATE TABLE nn_part_par (a int NOT NULL) PARTITION BY LIST (a);
CREATE TABLE nn_part_ch (a int CONSTRAINT nn_part_ch_nn NOT NULL);
ALTER TABLE nn_part_par ATTACH PARTITION nn_part_ch FOR VALUES IN (1);
SELECT * FROM pg_get_table_ddl('nn_part_ch'::regclass, owner => false);
DROP TABLE nn_part_par;

-- Named NOT NULL in an INHERITS child where the parent also gets a NOT NULL
-- later: the child name must survive via the inline CONSTRAINT clause so it
-- does not collide with the propagated parent NOT NULL.
CREATE TABLE nn_inh_par (a int);
CREATE TABLE nn_inh_ch (b int) INHERITS (nn_inh_par);
ALTER TABLE nn_inh_ch ADD CONSTRAINT nn_inh_ch_nn NOT NULL a;
ALTER TABLE nn_inh_par ADD CONSTRAINT nn_inh_par_nn NOT NULL a;
SELECT * FROM pg_get_table_ddl('nn_inh_ch'::regclass, owner => false);
DROP TABLE nn_inh_par CASCADE;

-- Invalid index (left by a failed CREATE INDEX CONCURRENTLY) must be skipped.
CREATE TABLE inv_idx (x int);
INSERT INTO inv_idx VALUES (1), (1);
CREATE UNIQUE INDEX CONCURRENTLY inv_idx_uidx ON inv_idx (x);
SELECT * FROM pg_get_table_ddl('inv_idx'::regclass, owner => false);
DROP TABLE inv_idx;

-- Partitioned index created with ON ONLY has indisvalid=false until child
-- indexes are attached, but must not be treated as a failed-CIC index.
CREATE TABLE parted_onlyi (a int) PARTITION BY RANGE (a);
CREATE TABLE parted_onlyi_1 PARTITION OF parted_onlyi FOR VALUES FROM (0) TO (100);
CREATE INDEX ON ONLY parted_onlyi (a);
SELECT * FROM pg_get_table_ddl('parted_onlyi'::regclass, owner => false);
DROP TABLE parted_onlyi;

-- NOT VALID CHECK must be emitted as ALTER TABLE ... ADD CONSTRAINT ... NOT VALID,
-- not inline in CREATE TABLE.  An inline constraint is always validated against
-- the empty table, which would silently flip convalidated to true on replay.
CREATE TABLE not_valid_chk (a int);
ALTER TABLE not_valid_chk ADD CONSTRAINT chk CHECK (a < 50) NOT VALID;
SELECT * FROM pg_get_table_ddl('not_valid_chk'::regclass, owner => false);
DROP TABLE not_valid_chk;

-- Auto-named NOT NULL on an INHERITS child's inherited column must be emitted
-- inline as "NOT NULL col" (no CONSTRAINT clause).  An out-of-line ALTER TABLE
-- would collide with the NOT NULL that INHERITS propagates from the parent.
CREATE TABLE nn_inh_auto_par (a int PRIMARY KEY);
CREATE TABLE nn_inh_auto_ch (PRIMARY KEY (a) DEFERRABLE) INHERITS (nn_inh_auto_par);
SELECT * FROM pg_get_table_ddl('nn_inh_auto_ch'::regclass, owner => false);
DROP TABLE nn_inh_auto_par CASCADE;

-- CLUSTER ON: emitted after the index is created.
CREATE TABLE cluster_tbl (id int, val text);
CREATE INDEX cluster_tbl_id ON cluster_tbl (id);
CLUSTER cluster_tbl USING cluster_tbl_id;
SELECT * FROM pg_get_table_ddl('cluster_tbl'::regclass, owner => false);
DROP TABLE cluster_tbl;

-- Disabled rule: DISABLE RULE must be emitted after CREATE RULE.
CREATE TABLE disabled_rule_tbl (id int);
CREATE RULE dr_rule AS ON INSERT TO disabled_rule_tbl DO NOTHING;
ALTER TABLE disabled_rule_tbl DISABLE RULE dr_rule;
SELECT * FROM pg_get_table_ddl('disabled_rule_tbl'::regclass, owner => false);
DROP TABLE disabled_rule_tbl;

-- Index statistics target on an expression index column.
CREATE TABLE idx_stat_tbl (c1 int);
CREATE INDEX idx_stat_idx ON idx_stat_tbl ((c1 + 1));
ALTER INDEX idx_stat_idx ALTER COLUMN 1 SET STATISTICS 400;
SELECT * FROM pg_get_table_ddl('idx_stat_tbl'::regclass, owner => false);
DROP TABLE idx_stat_tbl;

-- schema_qualified=false must drop the schema prefix from DEFAULT
-- expressions and inline CHECK bodies that reference same-schema
-- objects (sequence via nextval, function via direct call).  This
-- relies on the deparser respecting the narrowed search_path rather
-- than on substring stripping.
CREATE SCHEMA pgtbl_ddl_xref;
CREATE SEQUENCE pgtbl_ddl_xref.myseq;
CREATE FUNCTION pgtbl_ddl_xref.f(int) RETURNS int LANGUAGE sql IMMUTABLE
    AS 'SELECT $1';
CREATE TABLE pgtbl_ddl_xref.t (
    id  int DEFAULT nextval('pgtbl_ddl_xref.myseq'),
    val int,
    CONSTRAINT chk CHECK (pgtbl_ddl_xref.f(val) > 0)
);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_xref.t'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_xref CASCADE;

-- schema_qualified=false must NOT corrupt string literals whose
-- contents happen to contain the schema name followed by a dot.  String
-- literal text is output verbatim by the deparser and is unaffected by
-- search_path narrowing.
CREATE SCHEMA pgtbl_ddl_str;
CREATE TABLE pgtbl_ddl_str.p (id int, note text) PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_str.pc PARTITION OF pgtbl_ddl_str.p
    (CONSTRAINT chk CHECK (note <> 'pgtbl_ddl_str.secret'))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_str.pc'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_str CASCADE;

-- schema_qualified=false must NOT corrupt double-quoted identifiers
-- whose contents happen to contain the schema name followed by a dot
-- (for example a column literally named "<schema>.weird" inside that
-- schema).  The mechanism is purely search_path narrowing: the deparser
-- outputs attribute names verbatim from pg_attribute, so the quoted
-- identifier content is never examined for schema prefixes.  This holds
-- even when the schema name is a single letter.
CREATE SCHEMA pgtbl_ddl_qid;
CREATE TABLE pgtbl_ddl_qid.p (id int, "pgtbl_ddl_qid.weird" int)
    PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_qid.pc PARTITION OF pgtbl_ddl_qid.p
    (CONSTRAINT chk CHECK ("pgtbl_ddl_qid.weird" > 0))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_qid.pc'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_qid CASCADE;
-- Same with a short (single-letter) schema name to confirm there is no
-- minimum-length assumption in the stripping path.
CREATE SCHEMA pgtbl_ddl_q1;
CREATE TABLE pgtbl_ddl_q1.p (id int, "pgtbl_ddl_q1.weird" int)
    PARTITION BY RANGE (id);
CREATE TABLE pgtbl_ddl_q1.pc PARTITION OF pgtbl_ddl_q1.p
    (CONSTRAINT chk CHECK ("pgtbl_ddl_q1.weird" > 0))
    FOR VALUES FROM (0) TO (100);
SELECT * FROM pg_get_table_ddl('pgtbl_ddl_q1.pc'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA pgtbl_ddl_q1 CASCADE;

-- schema_qualified=false when the base schema name itself requires
-- quoting (its prefix starts with ").  Both forms of the prefix -
-- bare-lowercase and quoted - must be stripped from outer
-- ALTER TABLE / ON / CREATE INDEX prefixes, while inner quoted
-- identifiers that happen to begin the same way must be preserved.
CREATE SCHEMA "PgTbl-Ddl-Q";
CREATE TABLE "PgTbl-Ddl-Q"."T" (id int, val int,
    CONSTRAINT chk CHECK (val > 0));
CREATE INDEX "T_val_idx" ON "PgTbl-Ddl-Q"."T" (val);
SELECT * FROM pg_get_table_ddl('"PgTbl-Ddl-Q"."T"'::regclass,
                               owner => false,
                               schema_qualified => false);
DROP SCHEMA "PgTbl-Ddl-Q" CASCADE;

-- Error: not an ordinary or partitioned table.
CREATE VIEW v AS SELECT 1 AS x;
SELECT * FROM pg_get_table_ddl('v'::regclass);

CREATE SEQUENCE s;
SELECT * FROM pg_get_table_ddl('s'::regclass);

-- NULL argument returns no rows.
SELECT * FROM pg_get_table_ddl(NULL);

-- REPLICA IDENTITY USING INDEX validation: if the referenced index
-- would not be emitted (because its source kind is suppressed) but
-- replica_identity itself would be, the function raises an error so
-- the emitted DDL never dangles.  Exercise all three constraint-backed
-- forms (PK, UNIQUE, EXCLUSION) and a bare CREATE UNIQUE INDEX, in
-- both the except-list and only-list shapes.
--
-- PK-backed: except_kinds=primary_key without except_kinds=replica_identity.
CREATE TABLE ri_pk_excl (a int PRIMARY KEY);
ALTER TABLE ri_pk_excl REPLICA IDENTITY USING INDEX ri_pk_excl_pkey;
SELECT * FROM pg_get_table_ddl('ri_pk_excl'::regclass, owner => false, except_kinds => ARRAY['primary_key']);
-- Same call but also excluding replica_identity succeeds.
SELECT * FROM pg_get_table_ddl('ri_pk_excl'::regclass, owner => false, except_kinds => ARRAY['primary_key','replica_identity']);
DROP TABLE ri_pk_excl;

-- UNIQUE-constraint-backed replica identity index.
CREATE TABLE ri_uniq_excl (a int NOT NULL UNIQUE, b int);
ALTER TABLE ri_uniq_excl REPLICA IDENTITY USING INDEX ri_uniq_excl_a_key;
SELECT * FROM pg_get_table_ddl('ri_uniq_excl'::regclass, owner => false, except_kinds => ARRAY['unique']);
SELECT * FROM pg_get_table_ddl('ri_uniq_excl'::regclass, owner => false, except_kinds => ARRAY['unique','replica_identity']);
DROP TABLE ri_uniq_excl;

-- Bare CREATE UNIQUE INDEX (no backing constraint) used as REPLICA
-- IDENTITY: the index is emitted by the "index" kind, so excluding
-- "index" without also excluding "replica_identity" must error.
CREATE TABLE ri_idx_excl (a int NOT NULL, b int);
CREATE UNIQUE INDEX ri_idx_excl_a_uniq ON ri_idx_excl (a);
ALTER TABLE ri_idx_excl REPLICA IDENTITY USING INDEX ri_idx_excl_a_uniq;
SELECT * FROM pg_get_table_ddl('ri_idx_excl'::regclass, owner => false, except_kinds => ARRAY['index']);
SELECT * FROM pg_get_table_ddl('ri_idx_excl'::regclass, owner => false, except_kinds => ARRAY['index','replica_identity']);
DROP TABLE ri_idx_excl;

-- Include-side analog: only_kinds=replica_identity must include the kind
-- that emits the index, or the function errors.
CREATE TABLE ri_only (a int NOT NULL UNIQUE, b int);
ALTER TABLE ri_only REPLICA IDENTITY USING INDEX ri_only_a_key;
SELECT * FROM pg_get_table_ddl('ri_only'::regclass, owner => false, only_kinds => ARRAY['replica_identity']);
-- Including both kinds succeeds.
SELECT * FROM pg_get_table_ddl('ri_only'::regclass, owner => false, only_kinds => ARRAY['unique','replica_identity']);
DROP TABLE ri_only;

-- Per-kind only_kinds / except_kinds coverage.  For each kind in the vocabulary,
-- verify that only_kinds=K emits just that kind's output and that except_kinds=K
-- omits just that kind's output.  Kinds with no fixture above (trigger,
-- policy) are still recognized but currently emit nothing; only_kinds=K
-- returns zero rows for them.  Fixtures used:
--   idxd: PK + two secondary CREATE INDEX
--   cons: PK + UNIQUE + CHECK + FK (constraint-backed)
--   rt:   CREATE RULE
--   stx:  CREATE STATISTICS
--   rls:  ENABLE/FORCE ROW LEVEL SECURITY
--   ri_full: REPLICA IDENTITY FULL (no source-kind dependency)
CREATE TABLE excl_fix (rng int4range,
    EXCLUDE USING gist (rng WITH &&));

-- only_kinds=K: emit only kind K's statements.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['index']);
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['primary_key']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, only_kinds => ARRAY['unique']);
SELECT * FROM pg_get_table_ddl('excl_fix'::regclass, owner => false, only_kinds => ARRAY['exclusion']);
SELECT * FROM pg_get_table_ddl('rt'::regclass, owner => false, only_kinds => ARRAY['rule']);
SELECT * FROM pg_get_table_ddl('stx'::regclass, owner => false, only_kinds => ARRAY['statistics']);
SELECT * FROM pg_get_table_ddl('rls'::regclass, owner => false, only_kinds => ARRAY['rls']);
SELECT * FROM pg_get_table_ddl('ri_full'::regclass, owner => false, only_kinds => ARRAY['replica_identity']);
-- trigger / policy are not yet implemented; uncomment when
-- pg_get_trigger_ddl / pg_get_policy_ddl helpers land.
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['trigger']);
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['policy']);

-- except_kinds=K: emit everything except kind K's statements.  PK/UNIQUE/
-- INDEX are exercised on tables without REPLICA IDENTITY USING INDEX
-- so the validation does not trip.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['primary_key']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['unique']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, except_kinds => ARRAY['check']);
SELECT * FROM pg_get_table_ddl('excl_fix'::regclass, owner => false, except_kinds => ARRAY['exclusion']);
-- trigger / policy are not yet implemented; uncomment when
-- pg_get_trigger_ddl / pg_get_policy_ddl helpers land.
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, except_kinds => ARRAY['trigger']);
-- SELECT * FROM pg_get_table_ddl('basic'::regclass, owner => false, except_kinds => ARRAY['policy']);
-- except_kinds=table suppresses the CREATE TABLE + OWNER + child-default
-- SET DEFAULT + attoptions passes, leaving only the sub-object passes.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, except_kinds => ARRAY['table']);

-- Multi-kind compositions.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['table','index']);
SELECT * FROM pg_get_table_ddl('cons'::regclass, owner => false, only_kinds => ARRAY['primary_key','foreign_key']);
-- Duplicate entries in the list are silently de-duplicated by the
-- Bitmapset.
SELECT * FROM pg_get_table_ddl('idxd'::regclass, owner => false, only_kinds => ARRAY['index','index']);

DROP TABLE excl_fix;

-- Kind-filter tests on partitioned tables with indexes.
--
-- only_kinds=index on a partitioned table: only the parent's CREATE INDEX (ON ONLY)
-- is emitted; no CREATE TABLE, no partition children (KIND_PARTITION absent).
SELECT * FROM pg_get_table_ddl('parted_mixed'::regclass, owner => false,
                               only_kinds => ARRAY['index']);

-- except_kinds=index on a partitioned table: CREATE TABLE for the parent
-- and all children are emitted; no index statements.
SELECT * FROM pg_get_table_ddl('parted_mixed'::regclass, owner => false,
                               except_kinds => ARRAY['index']);

-- only_kinds=primary_key on a partitioned table: only the ALTER TABLE ADD
-- CONSTRAINT PK on the parent; the child's inherited PK (conislocal=false)
-- is skipped; no CREATE TABLE, no partition children.
SELECT * FROM pg_get_table_ddl('parted_pk'::regclass, owner => false,
                               only_kinds => ARRAY['primary_key']);

-- only_kinds=K on a table that does not have any K of that kind is a valid
-- filter and returns zero rows.  Tested previously with foreign_key
-- on 'refd'; here also rule, statistics, rls, replica_identity, and
-- exclusion on 'basic' (which has only PK + columns).
SELECT count(*) AS rule_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['rule']);
SELECT count(*) AS stats_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['statistics']);
SELECT count(*) AS rls_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['rls']);
SELECT count(*) AS ri_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['replica_identity']);
SELECT count(*) AS excl_rows
  FROM pg_get_table_ddl('basic'::regclass, owner => false, only_kinds => ARRAY['exclusion']);

-- Input-validation edge cases for the kind array.  All
-- of these raise an error; the function never reaches relation open.
-- Empty array:
SELECT * FROM pg_get_table_ddl('basic'::regclass, only_kinds => ARRAY[]::text[]);
-- NULL element:
SELECT * FROM pg_get_table_ddl('basic'::regclass, only_kinds => ARRAY[NULL::text]);
-- Unrecognized kind:
SELECT * FROM pg_get_table_ddl('basic'::regclass, only_kinds => ARRAY['no_such_kind']);
-- Same kind specified through both parameters is still mutex-rejected.
SELECT * FROM pg_get_table_ddl('basic'::regclass,
                               only_kinds => ARRAY['index'],
                               except_kinds => ARRAY['rule']);

-- Round-trip verification.  For every test table, capture the DDL the
-- function emits, drop the schema, replay each table's DDL in
-- dependency order, and confirm that pg_get_table_ddl on the recreated
-- relation matches the original line-for-line.  The final SELECT must
-- return zero rows.
CREATE TEMP TABLE pgtbl_ddl_rt_orig (name text, ord int, line text);
INSERT INTO pgtbl_ddl_rt_orig
SELECT t.name, o.ord, o.line
FROM (VALUES
        ('basic'), ('id_cols'), ('id_custom'), ('gen_cols'), ('gen_virtual'), ('storage_cols'),
        ('storage_plain'),
        ('refd'), ('cons'), ('nulls_nd'), ('idx_inc'),
        ('fk_acts_tgt'), ('fk_acts'),
        ('fk_upd_tgt'), ('fk_upd_acts'), ('fk_def_imm_tgt'), ('fk_def_imm'),
        ('notenf_tgt'), ('notenf'), ('self_ref'), ('temporal_pk'),
        ('idxd'),
        ('par'), ('ch'), ('attopt'),
        ('parted_range'), ('parted_range_1'), ('parted_range_def'),
        ('parted_hash'), ('parted_hash_0'),
        ('parted_list'),
        ('parted_idx'), ('parted_idx_a'),
        ('parted_plain'), ('parted_plain_a'),
        ('parted_pk'), ('parted_pk_a'),
        ('parted_sub'), ('parted_sub_a'), ('parted_sub_a1'),
        ('parted_child_idx'), ('parted_child_idx_a'),
        ('parted_mixed'), ('parted_mixed_a'),
        ('parted_fk_tgt'), ('parted_fk'), ('parted_fk_a'),
        ('rt_log'), ('rt'),
        ('stx'), ('rls'), ('ri_full'), ('ri_idx'), ('uno')
     ) AS t(name),
     LATERAL pg_get_table_ddl(('pgtbl_ddl_test.' || t.name)::regclass,
                              owner => false) WITH ORDINALITY o(line, ord);

DO $$
DECLARE
    tables CONSTANT text[] := ARRAY[
        'basic', 'id_cols', 'id_custom', 'gen_cols', 'gen_virtual', 'storage_cols',
        'storage_plain',
        'refd', 'cons', 'nulls_nd', 'idx_inc',
        'fk_acts_tgt', 'fk_acts',
        'fk_upd_tgt', 'fk_upd_acts', 'fk_def_imm_tgt', 'fk_def_imm',
        'notenf_tgt', 'notenf', 'self_ref', 'temporal_pk',
        'idxd',
        'par', 'ch', 'attopt',
        'parted_range', 'parted_range_1', 'parted_range_def',
        'parted_hash', 'parted_hash_0',
        'parted_list',
        'parted_idx', 'parted_idx_a',
        'parted_plain', 'parted_plain_a',
        'parted_pk', 'parted_pk_a',
        'parted_sub', 'parted_sub_a', 'parted_sub_a1',
        'parted_child_idx', 'parted_child_idx_a',
        'parted_mixed', 'parted_mixed_a',
        'parted_fk_tgt', 'parted_fk', 'parted_fk_a',
        'rt_log', 'rt',
        'stx', 'rls', 'ri_full', 'ri_idx', 'uno'
    ];
    t text;
    stmt text;
BEGIN
    DROP SCHEMA pgtbl_ddl_test CASCADE;
    CREATE SCHEMA pgtbl_ddl_test;
    FOREACH t IN ARRAY tables LOOP
        FOR stmt IN
            SELECT line FROM pgtbl_ddl_rt_orig WHERE name = t ORDER BY ord
        LOOP
            BEGIN
                EXECUTE stmt;
            EXCEPTION WHEN duplicate_table THEN
                NULL;  -- partition child already created by its parent's DDL
            END;
        END LOOP;
    END LOOP;
END $$;

WITH after_ddl AS (
    SELECT t.name, o.ord, o.line
    FROM (SELECT DISTINCT name FROM pgtbl_ddl_rt_orig) AS t,
         LATERAL pg_get_table_ddl(('pgtbl_ddl_test.' || t.name)::regclass,
                                  owner => false) WITH ORDINALITY o(line, ord)
)
(SELECT 'missing-in-copy' AS kind, name, ord, line FROM pgtbl_ddl_rt_orig
 EXCEPT
 SELECT 'missing-in-copy', name, ord, line FROM after_ddl)
UNION ALL
(SELECT 'extra-in-copy' AS kind, name, ord, line FROM after_ddl
 EXCEPT
 SELECT 'extra-in-copy', name, ord, line FROM pgtbl_ddl_rt_orig)
ORDER BY kind, name, ord;

-- Issue 1: CLUSTER ON must come after the constraint that creates the index.
CREATE TABLE clu (a int, b int);
ALTER TABLE clu ADD CONSTRAINT clu_pk PRIMARY KEY (a);
CLUSTER clu USING clu_pk;
SELECT stmt FROM pg_get_table_ddl('clu', owner => false) stmt;

-- Issue 3a: column SET STATISTICS.
CREATE TABLE cst (a int, b text);
ALTER TABLE cst ALTER COLUMN a SET STATISTICS 500;
ALTER TABLE cst ALTER COLUMN b SET STATISTICS 0;
SELECT stmt FROM pg_get_table_ddl('cst', owner => false) stmt;

-- Issue 3b: extended statistics SET STATISTICS.
CREATE TABLE ext_stat_tbl (a int, b int);
CREATE STATISTICS ext_stat_s (dependencies) ON a, b FROM ext_stat_tbl;
ALTER STATISTICS ext_stat_s SET STATISTICS 750;
SELECT stmt FROM pg_get_table_ddl('ext_stat_tbl', owner => false) stmt;

-- Issue 7: NOT NULL NOT VALID must not be emitted inline.
CREATE TABLE nnv (a int, b int);
ALTER TABLE nnv ADD CONSTRAINT nnv_a_nn NOT NULL a NOT VALID;
SELECT stmt FROM pg_get_table_ddl('nnv', owner => false) stmt;

-- Issue 9: ACCESS METHOD on partitioned parent.
CREATE TABLE pam (a int) PARTITION BY RANGE (a);
ALTER TABLE pam SET ACCESS METHOD heap;
SELECT stmt FROM pg_get_table_ddl('pam', owner => false) stmt;

-- Issue 11a: AS type in identity sequence options.
CREATE TABLE idt (a int GENERATED BY DEFAULT AS IDENTITY);
ALTER SEQUENCE idt_a_seq AS smallint;
SELECT stmt FROM pg_get_table_ddl('idt', owner => false) stmt;

-- Issue 2: CONSTRAINT WITH (fillfactor) and USING INDEX TABLESPACE must be
-- preserved in the ADD CONSTRAINT body.
CREATE TABLE pko (a int, b int);
ALTER TABLE pko ADD CONSTRAINT pko_pk PRIMARY KEY (a) WITH (fillfactor=50);
ALTER TABLE pko ADD CONSTRAINT pko_u UNIQUE (b) WITH (fillfactor=60);
SELECT stmt FROM pg_get_table_ddl('pko', owner => false) stmt;

-- Issue 2b: USING INDEX TABLESPACE in ADD CONSTRAINT.
CREATE TABLE pko_ts (a int, b int);
ALTER TABLE pko_ts ADD CONSTRAINT pko_ts_pk PRIMARY KEY (a)
    USING INDEX TABLESPACE regress_tblspace;
SELECT stmt FROM pg_get_table_ddl('pko_ts', owner => false) stmt;

-- Issue 4: toast.* storage parameters must appear in the WITH clause.
CREATE TABLE tst_toast (a int, b text)
    WITH (toast.autovacuum_enabled = false, fillfactor = 70);
SELECT stmt FROM pg_get_table_ddl('tst_toast', owner => false) stmt;

-- Issue 5: STORAGE and COMPRESSION overrides on inherited partition columns
-- must be emitted as post-CREATE ALTER TABLE statements.
CREATE TABLE ps_parent (a int, b text) PARTITION BY RANGE (a);
CREATE TABLE ps_child PARTITION OF ps_parent FOR VALUES FROM (0) TO (10);
ALTER TABLE ps_child ALTER COLUMN b SET STORAGE EXTERNAL;
SELECT stmt FROM pg_get_table_ddl('ps_parent', owner => false) stmt;

-- Issue 6: a foreign-table partition must produce a WARNING and be skipped
-- rather than causing an error.
CREATE FOREIGN DATA WRAPPER dummy_fdw;
CREATE SERVER dummy_srv FOREIGN DATA WRAPPER dummy_fdw;
CREATE TABLE fpar (a int) PARTITION BY RANGE (a);
CREATE TABLE fpar_1 PARTITION OF fpar FOR VALUES FROM (0) TO (10);
CREATE FOREIGN TABLE fpar_2 PARTITION OF fpar
    FOR VALUES FROM (10) TO (20) SERVER dummy_srv;
SELECT stmt FROM pg_get_table_ddl('fpar', owner => false) stmt;

-- Issue 8: a partition child index with a custom name must be emitted as
-- CREATE INDEX + ATTACH PARTITION; CLUSTER ON that custom index must also work.
CREATE TABLE cc (a int) PARTITION BY RANGE (a);
CREATE TABLE cc_1 PARTITION OF cc FOR VALUES FROM (0) TO (10);
CREATE INDEX ON ONLY cc (a);
CREATE INDEX cc_custom ON cc_1 (a);
ALTER INDEX cc_a_idx ATTACH PARTITION cc_custom;
ALTER TABLE cc_1 CLUSTER ON cc_custom;
SELECT stmt FROM pg_get_table_ddl('cc', owner => false) stmt;

-- Issue 10: tablespace => false must suppress TABLESPACE from both CREATE INDEX
-- and ADD CONSTRAINT ... USING INDEX TABLESPACE.
CREATE TABLE tsp (a int, b int);
CREATE INDEX tsp_a_idx ON tsp (a) TABLESPACE regress_tblspace;
ALTER TABLE tsp ADD CONSTRAINT tsp_pk PRIMARY KEY (b)
    USING INDEX TABLESPACE regress_tblspace;

-- With tablespace included (default):
SELECT stmt FROM pg_get_table_ddl('tsp', owner => false) stmt;

-- With tablespace suppressed:
SELECT stmt FROM pg_get_table_ddl('tsp', owner => false, tablespace => false) stmt;

-- Issue 11b: ALTER SEQUENCE SET UNLOGGED on an identity sequence must be
-- emitted as a post-CREATE ALTER SEQUENCE statement.
CREATE TABLE idl (a int GENERATED ALWAYS AS IDENTITY);
ALTER SEQUENCE idl_a_seq SET UNLOGGED;
SELECT stmt FROM pg_get_table_ddl('idl', owner => false) stmt;

-- Issue 12: ALTER INDEX ... ALTER COLUMN SET STATISTICS on a constraint-backed
-- index (PK, UNIQUE, EXCLUSION) must be emitted after the ADD CONSTRAINT.
-- EXCLUSION with an expression column is used because only expression columns
-- of an index support SET STATISTICS.
CREATE TABLE exs (a int, b int);
ALTER TABLE exs ADD CONSTRAINT exs_excl EXCLUDE USING btree ((a + 0) WITH =);
ALTER INDEX exs_excl ALTER COLUMN 1 SET STATISTICS 900;
SELECT stmt FROM pg_get_table_ddl('exs', owner => false) stmt;

-- Cleanup.
DROP SERVER dummy_srv CASCADE;
DROP FOREIGN DATA WRAPPER dummy_fdw CASCADE;
DROP SCHEMA pgtbl_ddl_test CASCADE;
