#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for cryptographic
#
# IDENTIFICATION
#    src/backend/crypto/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/crypto
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = kmgr.o

include $(top_srcdir)/src/backend/common.mk
