# This file is included into the Makefiles of subdirectories of ecpg/test/,
# so the file references have one more level of .. than you might expect.

override CFLAGS += $(PTHREAD_CFLAGS)

override LIBS += $(PTHREAD_LIBS)

ifdef USE_INSTALLED_ASSETS
ECPG = '$(DESTDIR)$(bindir)/ecpg' --regression -I'$(DESTDIR)$(includedir)' \
	-I'$(DESTDIR)$(pkgincludedir)/informix/esql'
override CPPFLAGS := -I'$(DESTDIR)$(includedir)' \
	-I'$(DESTDIR)$(pkgincludedir)/informix/esql' $(CPPFLAGS)
LDFLAGS_INTERNAL += -lecpg -lpgtypes $(libpq)
else
ECPG = ../../preproc/ecpg --regression -I$(srcdir)/../../include -I$(srcdir)
ECPG_DEP = ../../preproc/ecpg$(X)
override CPPFLAGS := -I../../include -I$(top_srcdir)/src/interfaces/ecpg/include \
	-I$(libpq_srcdir) $(CPPFLAGS)
LDFLAGS_INTERNAL += -L../../ecpglib -lecpg -L../../pgtypeslib -lpgtypes $(libpq)
endif

# Files that most or all ecpg preprocessor test outputs depend on
ECPG_TEST_DEPENDENCIES = $(ECPG_DEP) \
	$(srcdir)/../regression.h \
	$(srcdir)/../../include/sqlca.h \
	$(srcdir)/../../include/sqlda.h \
	$(srcdir)/../../include/sqltypes.h \
	$(srcdir)/../../include/sql3types.h

%: %.o
	$(CC) $(CFLAGS) $< $(LDFLAGS) $(LDFLAGS_EX) $(LIBS) -o $@

# Caution: this build rule is overridden in some child Makefiles
# where it's necessary to use nondefault switches to ecpg;
# make sure those rules match except for the extra switches.
%.c: %.pgc $(ECPG_TEST_DEPENDENCIES)
	$(ECPG) -o $@ $<

clean:
	rm -f $(TESTS) $(TESTS:%=%.o) $(TESTS:%=%.c)
