/* contrib/int16/int16--1.0.sql */

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "CREATE EXTENSION int16" to load this file. \quit

--
-- 128-bit signed integer data type.
--

-- Shell type
CREATE TYPE int16;

--
-- Input/output functions
--
CREATE FUNCTION int16in(cstring)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16out(int16)
RETURNS cstring
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16recv(internal)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16send(int16)
RETURNS bytea
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- The type itself
--
CREATE TYPE int16 (
    INPUT          = int16in,
    OUTPUT         = int16out,
    RECEIVE        = int16recv,
    SEND           = int16send,
    INTERNALLENGTH = 16,
    ALIGNMENT      = double,
    PASSEDBYVALUE  = false,
    CATEGORY       = 'N'
);

--
-- Arithmetic functions (int16 vs int16)
--
CREATE FUNCTION int16pl(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16mi(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16mul(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16div(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16mod(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16um(int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16up(int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16abs(int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- Comparison functions (int16 vs int16)
--
CREATE FUNCTION int16eq(int16, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16ne(int16, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16lt(int16, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16gt(int16, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16le(int16, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16ge(int16, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16_cmp(int16, int16)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- Operators (int16 vs int16)
--
CREATE OPERATOR + (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16pl,
    COMMUTATOR = +
);

CREATE OPERATOR - (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16mi
);

CREATE OPERATOR * (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16mul,
    COMMUTATOR = *
);

CREATE OPERATOR / (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16div
);

CREATE OPERATOR % (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16mod
);

CREATE OPERATOR - (
    RIGHTARG = int16,
    PROCEDURE = int16um
);

CREATE OPERATOR + (
    RIGHTARG = int16,
    PROCEDURE = int16up
);

CREATE OPERATOR @ (
    RIGHTARG = int16,
    PROCEDURE = int16abs
);

CREATE OPERATOR = (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Bitwise functions and operators
--
CREATE FUNCTION int16and(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16or(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16xor(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16not(int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16shl(int16, int4)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16shr(int16, int4)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR & (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16and,
    COMMUTATOR = &
);

CREATE OPERATOR | (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16or,
    COMMUTATOR = |
);

CREATE OPERATOR # (
    LEFTARG = int16, RIGHTARG = int16,
    PROCEDURE = int16xor,
    COMMUTATOR = #
);

CREATE OPERATOR ~ (
    RIGHTARG = int16,
    PROCEDURE = int16not
);

CREATE OPERATOR << (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int16shl
);

CREATE OPERATOR >> (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int16shr
);

--
-- Conversion functions (for casts)
--
CREATE FUNCTION int16(int8)
RETURNS int16
AS 'MODULE_PATHNAME', 'int16_from_int8'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int8(int16)
RETURNS int8
AS 'MODULE_PATHNAME', 'int16_to_int8'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16(int4)
RETURNS int16
AS 'MODULE_PATHNAME', 'int16_from_int4'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int4(int16)
RETURNS int4
AS 'MODULE_PATHNAME', 'int16_to_int4'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16(int2)
RETURNS int16
AS 'MODULE_PATHNAME', 'int16_from_int2'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int2(int16)
RETURNS int2
AS 'MODULE_PATHNAME', 'int16_to_int2'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- Casts
--
CREATE CAST (int8 AS int16) WITH FUNCTION int16(int8) AS IMPLICIT;
CREATE CAST (int16 AS int8) WITH FUNCTION int8(int16) AS ASSIGNMENT;
CREATE CAST (int4 AS int16) WITH FUNCTION int16(int4) AS IMPLICIT;
CREATE CAST (int16 AS int4) WITH FUNCTION int4(int16) AS ASSIGNMENT;
CREATE CAST (int2 AS int16) WITH FUNCTION int16(int2) AS IMPLICIT;
CREATE CAST (int16 AS int2) WITH FUNCTION int2(int16) AS ASSIGNMENT;

-- int16 ↔ numeric casts (matching int8↔numeric policy: widening=implicit, narrowing=assignment)
CREATE FUNCTION int16_numeric(int16)
RETURNS numeric
AS 'MODULE_PATHNAME', 'int16_numeric'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION numeric_int16(numeric)
RETURNS int16
AS 'MODULE_PATHNAME', 'numeric_int16'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE CAST (int16 AS numeric) WITH FUNCTION int16_numeric(int16) AS IMPLICIT;
CREATE CAST (numeric AS int16) WITH FUNCTION numeric_int16(numeric) AS ASSIGNMENT;

--
-- Cross-type arithmetic: int16 op int8
--
CREATE FUNCTION int168pl(int16, int8)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168mi(int16, int8)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168mul(int16, int8)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168div(int16, int8)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR + (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168pl
);

CREATE OPERATOR - (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168mi
);

CREATE OPERATOR * (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168mul
);

CREATE OPERATOR / (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168div
);

--
-- Cross-type arithmetic: int8 op int16
--
CREATE FUNCTION int816pl(int8, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816mi(int8, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816mul(int8, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816div(int8, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR + (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816pl
);

CREATE OPERATOR - (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816mi
);

CREATE OPERATOR * (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816mul
);

CREATE OPERATOR / (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816div
);

--
-- Cross-type arithmetic: int16 op int4
--
CREATE FUNCTION int164pl(int16, int4)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164mi(int16, int4)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164mul(int16, int4)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164div(int16, int4)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR + (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164pl
);

CREATE OPERATOR - (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164mi
);

CREATE OPERATOR * (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164mul
);

CREATE OPERATOR / (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164div
);

--
-- Cross-type arithmetic: int4 op int16
--
CREATE FUNCTION int416pl(int4, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416mi(int4, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416mul(int4, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416div(int4, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR + (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416pl
);

CREATE OPERATOR - (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416mi
);

CREATE OPERATOR * (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416mul
);

CREATE OPERATOR / (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416div
);

--
-- Cross-type arithmetic: int16 op int2
--
CREATE FUNCTION int162pl(int16, int2)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162mi(int16, int2)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162mul(int16, int2)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162div(int16, int2)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR + (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162pl
);

CREATE OPERATOR - (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162mi
);

CREATE OPERATOR * (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162mul
);

CREATE OPERATOR / (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162div
);

--
-- Cross-type arithmetic: int2 op int16
--
CREATE FUNCTION int216pl(int2, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216mi(int2, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216mul(int2, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216div(int2, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR + (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216pl
);

CREATE OPERATOR - (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216mi
);

CREATE OPERATOR * (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216mul
);

CREATE OPERATOR / (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216div
);

--
-- Cross-type comparison: int16 vs int8
--
CREATE FUNCTION int168eq(int16, int8)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168ne(int16, int8)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168lt(int16, int8)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168gt(int16, int8)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168le(int16, int8)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168ge(int16, int8)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int168cmp(int16, int8)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR = (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int16, RIGHTARG = int8,
    PROCEDURE = int168ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Cross-type comparison: int8 vs int16
--
CREATE FUNCTION int816eq(int8, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816ne(int8, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816lt(int8, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816gt(int8, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816le(int8, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816ge(int8, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int816cmp(int8, int16)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR = (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int8, RIGHTARG = int16,
    PROCEDURE = int816ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Cross-type comparison: int16 vs int4
--
CREATE FUNCTION int164eq(int16, int4)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164ne(int16, int4)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164lt(int16, int4)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164gt(int16, int4)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164le(int16, int4)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164ge(int16, int4)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int164cmp(int16, int4)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR = (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int16, RIGHTARG = int4,
    PROCEDURE = int164ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Cross-type comparison: int4 vs int16
--
CREATE FUNCTION int416eq(int4, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416ne(int4, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416lt(int4, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416gt(int4, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416le(int4, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416ge(int4, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int416cmp(int4, int16)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR = (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int4, RIGHTARG = int16,
    PROCEDURE = int416ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Cross-type comparison: int16 vs int2
--
CREATE FUNCTION int162eq(int16, int2)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162ne(int16, int2)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162lt(int16, int2)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162gt(int16, int2)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162le(int16, int2)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162ge(int16, int2)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int162cmp(int16, int2)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR = (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int16, RIGHTARG = int2,
    PROCEDURE = int162ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Cross-type comparison: int2 vs int16
--
CREATE FUNCTION int216eq(int2, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216ne(int2, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216lt(int2, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216gt(int2, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216le(int2, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216ge(int2, int16)
RETURNS bool
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int216cmp(int2, int16)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE OPERATOR = (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216eq,
    COMMUTATOR = =, NEGATOR = <>,
    RESTRICT = eqsel, JOIN = eqjoinsel,
    HASHES, MERGES
);

CREATE OPERATOR <> (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216ne,
    COMMUTATOR = <>, NEGATOR = =,
    RESTRICT = neqsel, JOIN = neqjoinsel
);

CREATE OPERATOR < (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216lt,
    COMMUTATOR = >, NEGATOR = >=,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR > (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216gt,
    COMMUTATOR = <, NEGATOR = <=,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

CREATE OPERATOR <= (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216le,
    COMMUTATOR = >=, NEGATOR = >,
    RESTRICT = scalarltsel, JOIN = scalarltjoinsel
);

CREATE OPERATOR >= (
    LEFTARG = int2, RIGHTARG = int16,
    PROCEDURE = int216ge,
    COMMUTATOR = <=, NEGATOR = <,
    RESTRICT = scalargtsel, JOIN = scalargtjoinsel
);

--
-- Hash function
--
CREATE FUNCTION int16_hash(int16)
RETURNS int4
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- Aggregate support functions
--
CREATE FUNCTION int16larger(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16smaller(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

-- sum(int16) uses int16pl as both transition and combine function

-- avg(int16) uses a dedicated state type to hold sum + count
CREATE TYPE int16_avg_state;

CREATE FUNCTION int16_avg_state_in(cstring)
RETURNS int16_avg_state
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16_avg_state_out(int16_avg_state)
RETURNS cstring
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE TYPE int16_avg_state (
    INPUT          = int16_avg_state_in,
    OUTPUT         = int16_avg_state_out,
    INTERNALLENGTH = 24,
    ALIGNMENT      = double,
    PASSEDBYVALUE  = false
);

CREATE FUNCTION int16_avg_accum(int16_avg_state, int16)
RETURNS int16_avg_state
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION int16_avg_accum_combine(int16_avg_state, int16_avg_state)
RETURNS int16_avg_state
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

CREATE FUNCTION int16_avg(int16_avg_state)
RETURNS numeric
AS 'MODULE_PATHNAME'
LANGUAGE C IMMUTABLE PARALLEL SAFE;

--
-- Aggregates
--
CREATE AGGREGATE sum(int16) (
    SFUNC = int16pl,
    STYPE = int16,
    COMBINEFUNC = int16pl,
    PARALLEL = SAFE
);

CREATE AGGREGATE avg(int16) (
    SFUNC = int16_avg_accum,
    STYPE = int16_avg_state,
    FINALFUNC = int16_avg,
    COMBINEFUNC = int16_avg_accum_combine,
    PARALLEL = SAFE
);

CREATE AGGREGATE min(int16) (
    SFUNC = int16smaller,
    STYPE = int16,
    COMBINEFUNC = int16smaller,
    PARALLEL = SAFE
);

CREATE AGGREGATE max(int16) (
    SFUNC = int16larger,
    STYPE = int16,
    COMBINEFUNC = int16larger,
    PARALLEL = SAFE
);

--
-- Additional mathematical functions (gcd, lcm, factorial)
--
CREATE FUNCTION gcd(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME', 'int16gcd'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION lcm(int16, int16)
RETURNS int16
AS 'MODULE_PATHNAME', 'int16lcm'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION factorial(int16)
RETURNS numeric
AS 'MODULE_PATHNAME', 'int16factorial'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- Set-returning function: generate_series
--
CREATE FUNCTION generate_series(int16, int16)
RETURNS SETOF int16
AS 'MODULE_PATHNAME', 'generate_series_int16'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE
ROWS 1000;

CREATE FUNCTION generate_series(int16, int16, int16)
RETURNS SETOF int16
AS 'MODULE_PATHNAME', 'generate_series_step_int16'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE
ROWS 1000;

--
-- in_range support function for window frames
--
CREATE FUNCTION in_range(int16, int16, int16, boolean, boolean)
RETURNS boolean
AS 'MODULE_PATHNAME', 'in_range_int16_int16'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- B-tree support functions
--
CREATE FUNCTION int16sortsupport(internal)
RETURNS void
AS 'MODULE_PATHNAME', 'int16sortsupport'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

CREATE FUNCTION int16skipsupport(internal)
RETURNS void
AS 'MODULE_PATHNAME', 'int16skipsupport'
LANGUAGE C IMMUTABLE STRICT PARALLEL SAFE;

--
-- B-tree operator class
--
CREATE OPERATOR CLASS int16_ops
    DEFAULT FOR TYPE int16 USING btree AS
        OPERATOR        1       < ,
        OPERATOR        2       <= ,
        OPERATOR        3       = ,
        OPERATOR        4       >= ,
        OPERATOR        5       > ,
        FUNCTION        1       int16_cmp(int16, int16),
        FUNCTION        2       int16sortsupport(internal),
        FUNCTION        3       in_range(int16, int16, int16, boolean, boolean),
        FUNCTION        4       btequalimage(oid),
        FUNCTION        6       int16skipsupport(internal);

--
-- Hash operator class
--
CREATE OPERATOR CLASS int16_ops
    DEFAULT FOR TYPE int16 USING hash AS
        OPERATOR        1       = ,
        FUNCTION        1       int16_hash(int16);
