#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/toast
#
# IDENTIFICATION
#    src/backend/access/toast/heap/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/toast
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	generic_toaster.o

include $(top_srcdir)/src/backend/common.mk
