#!/usr/bin/env python3

import os
import shlex
import sys

mesonintrospect = os.environ['MESONINTROSPECT']
components = shlex.split(mesonintrospect)

if len(components) < 2:
    print('expected more than two components, got: %s' % components)
    sys.exit(1)

if components[-1] != 'introspect':
    print('expected introspection at the end')
    sys.exit(1)

print('\n'.join(components[:-1]), end='')

sys.exit(0)
