#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(description='generate PostgreSQL rc file')

parser.add_argument('INPUT', type=argparse.FileType('r'))
parser.add_argument('-o', '--output', type=argparse.FileType('w'), required=True)
parser.add_argument('--depfile', type=argparse.FileType('w'), required=False)

parser.add_argument('--FILEDESC', type=str, required=True)
parser.add_argument('--NAME', type=str, required=True)
parser.add_argument('--VFT_TYPE', type=str, required=True)
parser.add_argument('--FILEENDING', type=str, required=True)
parser.add_argument('--ICO', type=str)


args = parser.parse_args()

data = args.INPUT.read()

data = data.replace('@FILEDESC@', args.FILEDESC)
data = data.replace('@NAME@', args.NAME)
data = data.replace('@VFT_TYPE@', args.VFT_TYPE)
data = data.replace('@FILEENDING@', args.FILEENDING)

if args.ICO:
   data = data.replace('@ICO@', args.ICO)
   if args.depfile:
       args.depfile.write("{0} : {1}\n".format(args.INPUT.name, args.ICO))
else:
   data = data.replace("IDI_ICON ICON \"@ICO@\"\n", '')

args.output.write(data)
