#!/usr/bin/env python3

import argparse
import shutil
import subprocess
import os

parser = argparse.ArgumentParser()

parser.add_argument('--srcdir', help='source directory of test', type=str)
parser.add_argument('--basedir', help='base directory of test', type=str)
parser.add_argument('--builddir', help='build directory of meson build', type=str)
parser.add_argument('--testgroup', help='test group', type=str)
parser.add_argument('--testname', help='test name', type=str)

args, test_command = parser.parse_known_args()

args.testname = args.testname.rstrip('.pl')

testdir = '{}/testrun/{}/{}'.format(args.basedir, args.testgroup, args.testname)

print('# executing test in {} group {} test {}, builddir {}'
  .format(testdir, args.testgroup, args.testname, args.builddir))

if os.path.exists(testdir) and os.path.isdir(testdir):
  shutil.rmtree(testdir)
os.makedirs(testdir)

os.chdir(args.srcdir)

env_dict = {**os.environ, 'TESTOUTDIR': testdir, 'TESTDIR': args.builddir}
subprocess.run(test_command, env=env_dict, check=True)
